### ISSUE TITLE
"Guidance Needed: Contributing to Python Question Bank Project"

### ISSUE THREAD

**Issue by Sanmita-Paul** [animator/learn-python#100]
@animator 
Seeking advice to contribute to a Python question bank project under "Learn Python."

**Comment by animator** [comment]
This will come once all other topic materials are completed. So you can ignore it for now.

**Comment by Sanmita-Paul** [comment]
@animator 
sir as i'm new to open source contribution I would like your guide on selecting topic.
My area of expertise is Python and Sql.
