### ISSUE TITLE
Add Usage of Matplotlib

### ISSUE THREAD

**Issue by riyaaryan2004** [animator/learn-python#102]
I can add the usage of the library of how specific points are plotted using this lib.

**Comment by aminasaeed223** [comment]
Assign this task to me as well.

**Comment by hasmithagunda123** [comment]
Assign this task to me as well

**Comment by ArismitaM** [comment]
I have worked with matplotlib for a hackathon before and would like to contribute to it here, please assign this task to me

**Comment by animator** [comment]
Closing as no PR has been raised so far.
