### ISSUE TITLE
Manupulating data in pandas

### ISSUE THREAD

**Issue by Kazasunitha** [animator/learn-python#1023]
Manupulating data in pandas consists of adding new column to existing data,delete the row or columns of data,iterating over rows and columns, truncate a dataframe before or after some index value ..etc

**Comment by Kazasunitha** [comment]
I request you to assign this task for me under Gssoc-24 and label  it

**Comment by tkshsbcue** [comment]
I request u to assign me this issue

**Comment by Kazasunitha** [comment]
Could you plz re assign it for me

**Comment by Kazasunitha** [comment]
Plz assign it to me I have been in work assign it to me I will complete it now
