### ISSUE TITLE
[Mini Project]- simple to-do list

### ISSUE THREAD

**Issue by miss-panchal** [animator/learn-python#104]
a simple to-do list without importing any library or using any database.
1. using for loop
2. Add Task , Show Tasks , Mark Task as Done feature

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to get the PR of the assigned issue merged before being assigned a new issue.

**Comment by harinisayani** [comment]
Hi,
I am contributing under GSSOc'24.
I am having prior experience in developing mini project - simple to-do-list. Could you please assign it to me.
