### ISSUE TITLE
Mini Project - Password Generator

### ISSUE THREAD

**Issue by Sunainabhave** [animator/learn-python#106]
This generator creates random passwords after the user specifies the desired length and character set ensuring security.

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to get the PR of the assigned issue merged before being assigned a new issue.

**Comment by Vinayakkh** [comment]
I can make this project by javascript in which random character is generated of selected range of user

**Comment by harikasayani** [comment]
Hi,
I am GSSOC'24 Contributor.
Could you please assign this task to me. I have experience in developing password generator project using HTML, CSS and JavaScript.

**Comment by Yodha-Sudarsi** [comment]
Hey @animator , I'd like to contribute to this Mini Project. Could you please assign this task to me ?

**Comment by deekshithapalla** [comment]
I would like to work on this issue using graphical user interface (Python).
Please assign this task to me.
