### ISSUE TITLE
Mini Project - Hangman Game

### ISSUE THREAD

**Issue by MahraibFatima** [animator/learn-python#108]
Features: 
- Randomly generated words for each game.
- Visual representation of the Hangman.
- User-friendly interface.
- Guess letters to uncover the hidden word.
- Have a limited number of attempts to guess the word correctly.

**Comment by MahraibFatima** [comment]
@animator a quick question, have I do all the changes and code in .md extension OR can do this in different .py extension using OOP concepts as well?

**Comment by animator** [comment]
It is a book. Everything has to be presented in markdown format.

**Comment by RasagnaRayasam** [comment]
I am proficient in Python and being a beginner in open source contribution. Please assign me this issue
