### ISSUE TITLE
Database Interaction

### ISSUE THREAD

**Issue by kdanjana** [animator/learn-python#11]
I want to  add python interaction with databses(MYSQL in particular) , notes about it . Please assign it to me.

**Comment by SohaFarhana** [comment]
Helloo
I am a contributor of Girl Script 2024 
I would like to work on this area
I have a good knowledge on DBMS

**Comment by RishitaChourey** [comment]
Hey,I am a GSSoc'24 contributor and would like to work on this issue as i have worked on multiple projects around python,mysql,mongodb etc . please assign it to me.

**Comment by animator** [comment]
@kdanjana @SohaFarhana @RishitaChourey Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
