### ISSUE TITLE
Basic Quiz game

### ISSUE THREAD

**Issue by ishaanv1206** [animator/learn-python#110]
I want to develop a basic  mcq quiz game where user can select from a particular genre and user gets the points scored in the end

**Comment by SaiSruthisri** [comment]
Hi @animator 
I have a prior experience on making quizz games using python & so I would like to contribute to this issue.
You can check my work in my github ->
https://github.com/SaiSruthisri/mahabharatam-quest

**Comment by hasmithagunda123** [comment]
I had already implemented this few weeks ago and worked on it. Kindly assign me this issue

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
