### ISSUE TITLE
Add Cross Validation vs Testing Data

### ISSUE THREAD

**Issue by Soubeer** [animator/learn-python#1123]
There is a need for clarification on the distinction between cross-validation and testing data in our machine learning workflows. Cross-validation is a technique used to evaluate the performance of a model by partitioning the data into subsets, training the model on some subsets while validating on others, to ensure it generalizes well to unseen data. Testing data, on the other hand, is a separate dataset not used during the training process, reserved exclusively for the final evaluation of the model's performance. 

This issue aims to enhance our README with a comprehensive explanation of these concepts, including their purposes, differences, and best practices for their use.

I would like to take this task under GSSOC'24.

Thank You

**Comment by ashitaprasad** [comment]
Reviewing & Merging PRs take time. I recommend you to contribute to some other project.
Ref: https://github.com/GSSoC24/Contributor/discussions/94?sort=new#discussioncomment-9695357
