### ISSUE TITLE
[Add Content] Magic Methods in Python

### ISSUE THREAD

**Issue by somyasaxena01** [animator/learn-python#1132]
Hello @animator , I am a GSSoC'24 Contributor. I would like to contribute to your project by adding content on Magic Methods in Python. Please assign this issue to me.
Topics Covered :- 
   1) What are Magic Methods ?
   2) List of Magic Methods
   3) Magic Methods with examples

**Comment by tanu91112** [comment]
Hello @animator , I am a GSSoC'24 Contributor. Please assign this issue to me.

**Comment by somyasaxena01** [comment]
I went through the pull requests and I saw one for the Magic Methods already present there, should I be working on adding the content or not ?

**Comment by somyasaxena01** [comment]
@animator I went through the pull requests and I saw one for the Magic Methods already present there, should I be working on adding the content or not ?
