### ISSUE TITLE
Basic Mathematics for python

### ISSUE THREAD

**Issue by AritraCh2005** [animator/learn-python#115]
Hello, @animator,  I would like to add some basic mathematics like definition of scalars, vectors, tensors and their usage which would be useful while working with nd arrays, matrices etc..I would also like to add to this section basic operations of matrices like addition, subtraction, transpose which would be really helpful for beginners...

**Comment by Vedant285** [comment]
Hy, @animator I would like to add some advanced maths here and it will be a great experience for people...

**Comment by Praneeth2312** [comment]
hello sir @animator ,i would like to contribute to this issue please assign this to me.

**Comment by hasmithagunda123** [comment]
hello I have much expirence in python . please assign me this issue

**Comment by prajwaldp223** [comment]
can i work on this task?

**Comment by RasagnaRayasam** [comment]
I am a python developer and I believe I can do this. Please assign me the issue.Thank you
