### ISSUE TITLE
add content to tuple 

### ISSUE THREAD

**Issue by Ashana2004** [animator/learn-python#1168]
hello @animator  plz assign me under Gssoc's 2024..as i  want to add up to tuple under tuples modification
                                                                                                                                                           
Tuples are immutable but they can be modified by firstly typecasting them into list then modifying the list and then again converting the list into tuples ...hence they can be modified.

example :
# Given tuple
my_tuple = (100,200,300,400,700)

# Convert tuple to list
my_list = list(my_tuple)

# Print the result
print(my_list)
output: [100,200,300,400,700]
now converting or replacing 700 with 900

input:
index = my_list.index(700)
my_list[index] = 900

# Print the result
print(my_list)
output: [100,200,300,400,900]

now converting list into tuple 
# Convert list back to tuple
new_tuple = tuple(my_list)

# Print the result
print(new_tuple)

hence , we get the modified tuple as
(100,200,300,400,900)

**Comment by Aditii-1** [comment]
I would like to work on this issue. Could you please assign me this issue under GSSoC'24. @animator
