### ISSUE TITLE
Adding AlexNet Architecture

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#1181]
I want to add alexnet architecture explaining how many layers it has, function of each layer, etc. Please assign this issue to me.

**Comment by TWmin13** [comment]
Adding AlexNet Architecture 

Please assign this issue to me. Would like to add content  about the architecture with python codes using VisualKeras modules for visual representation.

**Comment by TWmin13** [comment]
> Adding AlexNet Architecture
> 
> Please assign this issue to me. Would like to add content about the architecture with python codes using VisualKeras modules for visual representation.

as part of  GSSOC'24

**Comment by Ishita-Jena** [comment]
There was a conflict in the open pr which i resolved. Please review pr #1095 so I can work on new issues. Thank you.
