### ISSUE TITLE
Adding Section : pandas Library

### ISSUE THREAD

**Issue by mukilan2815** [animator/learn-python#1183]
I can add Data Cleaning and Preparation Topic in pandas with some examples. 
Please assign under GSSOC'24

**Comment by Rajendran2201** [comment]
I had studied pandas in my last semester. I can provide good resource for pandas library. Kindly assign me under Gssoc'24.
Thank you!

**Comment by mukilan2815** [comment]
@Rajendran2201 I have completed it bro

**Comment by Rajendran2201** [comment]
Okay bro, No issues go ahead.
Thank you for letting me know.
