### ISSUE TITLE
Adding advanced concepts of function

### ISSUE THREAD

**Issue by Siddhi-Naik18** [animator/learn-python#1189]
Types of function:
Default values 
Keyword arguments
Variable-length arguments
iterators
generators
decorators

I would like to work on this issue. I am a GSOC contributor

**Comment by anshikatiwari20** [comment]
@animator I am a GSSoC contributor and would like to work on issue #1189 to add advanced concepts of functions as requested. Could you please assign this issue to me and add the appropriate label? Thank you!

**Comment by anshikatiwari20** [comment]
I am a GSSoC contributor and would like to work on issue https://github.com/animator/learn-python/issues/1189 to add advanced concepts of functions as requested. Could you please assign this issue to me and add the appropriate label? Thank you!
