### ISSUE TITLE
Okay have a cup of coffee ☕ & lets talk about OOPS in Python 🐍 

### ISSUE THREAD

**Issue by prasad-chavan1** [animator/learn-python#12]
<b> Understanding </b>
- classes
- objects 
- inheritance 
- polymorphism 
- encapsulation
- abstraction 

are imp concepts for developers working with Python. 
Hope you'll assign it to me 
<b>
Waitttt waitt dont leave have a sip of coffee again ☕ </b>

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by prasad-chavan1** [comment]
> I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

raise PR

**Comment by PilotAxis** [comment]
Hi @Santhosh-Siddhardha , I am a GSSoC'24 Contributor. I would like to contribute in this, please assign this issue to me. I have a clear understanding of OOPs in Python (Classes, Objects, Encapsulation, Abstraction, Inheritance and Polymorphism). I hope you'll assign this issue to me.

**Comment by prasad-chavan1** [comment]
> Hi @Santhosh-Siddhardha , I am a GSSoC'24 Contributor. I would like to contribute in this, please assign this issue to me. I have a clear understanding of OOPs in Python (Classes, Objects, Encapsulation, Abstraction, Inheritance and Polymorphism). I hope you'll assign this issue to me.

no need to assign just raise PR

**Comment by Kirti-Pant** [comment]
I am a GSSoC'24 contributor, please assign me this issue under GSSoC'24

**Comment by prasad-chavan1** [comment]
> I am a GSSoC'24 contributor, please assign me this issue under GSSoC'24

Just raise PR no need to assign

**Comment by animator** [comment]
@prasad-chavan1 @Kirti-Pant @anvishelar Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
