### ISSUE TITLE
Introduction to Bar Plots in Plotly

### ISSUE THREAD

**Issue by manasdeshpande** [animator/learn-python#1231]
I want to contribute a new section in [plotting-visualisation](https://github.com/animator/learn-python/tree/main/contrib/plotting-visualization) directory explaining the generation and manipulation of Bar Plots using Plotly in Python. I will create a comprehensive guide on how to generate various types of Bar Plots using Plotly.

Expected Level: Level 2

@animator Please assign this issue to me under GSSoC'24.

**Comment by piyush-poddar** [comment]
This issue #1169 is already there and a [PR](https://github.com/animator/learn-python/pull/1235) has also been raised for the same. If you want, you can contribute more on the topic after its merged.
