### ISSUE TITLE
Adding about Slicing Concept

### ISSUE THREAD

**Issue by Sagarika-Dubey** [animator/learn-python#126]
We can add the slicing concept and which data structures of Python allows slicing under the List part where you described indexing.

**Comment by govinddwivedigit** [comment]
I want to work on this issue , kindly assign this to me.

**Comment by Kazasunitha** [comment]
I want to add about the slicing concept in python .Slicing is used to extract the specific locations data from array or list. Slicing is done by using list[begin_index : End_index].So please assign this task for me under GSSoC'24.

**Comment by AmruthaPariprolu** [comment]
hey i would like to work on this
kindly assign this task to me under GSSOC'24

**Comment by animator** [comment]
Read properly. Slicing is already explained.
