### ISSUE TITLE
Add doubly linked list

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#1277]
I want to add doubly linked list which will cover operations like insertion, deletion, search and reversal. Please assign this issue to me.

**Comment by Ishita-Jena** [comment]
@ashitaprasad Would you please tell me which topics you're accepting now?

**Comment by ashitaprasad** [comment]
You can check here - https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md#how-can-i-contribute

**Comment by Ishita-Jena** [comment]
I did raise 2 issue related to machine learning - #1237 and #1181 but they were closed
