### ISSUE TITLE
Add about Selenium in Web-scrapping Module

### ISSUE THREAD

**Issue by Shraman-jain** [animator/learn-python#1278]
I want to add working of selenium and also want to add real world example of scrapping data using selenium. Please assign this issue to me under gssoc24

**Comment by ashitaprasad** [comment]
Since we take longer time to review PRs.
We recommend you to contribute to other GSSoC project.
Thanks.

**Comment by sanjay-kv** [comment]
@ashitaprasad Could you please send me a invite to the repo. I need to manage some labels. 
I have sent official mail on the same.

**Comment by ashitaprasad** [comment]
@sanjay-kv you can raise an issue in case you find any issues with the labels, we will fix it.
You don't need an invite for the same.
