### ISSUE TITLE
Mini Project: Basic Calculator

### ISSUE THREAD

**Issue by Sagarika-Dubey** [animator/learn-python#128]
We can Add a basic calculator as a mini project

**Comment by 7AAKANSHA** [comment]
HELLO  
I'm a contributor in GSSOC and would like to contribute on this section , I'm well versed with Python .
I would like to contribute to this section on creating a basic calculator if you could assign it to me. I'll do my work responsibly.

**Comment by SaiSruthisri** [comment]
Hi! Iam a GSSOC'24 contributor I have already sent a pr for this issue kindly please review it & if satisfied assign this task to me & would highly appreciate if you add gssoc label with appropiate level (1/2/3) , as it is only way for us contributors to have our contribution counted under gssoc'24.Thank you!

**Comment by Akshitha28112004** [comment]
Hey, I am good at python and I already have a code for this. Can you please assign me the issue under gssoc'24 ?

**Comment by Sagarika-Dubey** [comment]
@animator the code isn't copied!!!
I have made my Python base from that website so the ofcourse my approach of coding will be similar to that. The code isn't coped from anywhere.
