### ISSUE TITLE
Add Recurrent Neural Network (RNN)

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#1285]
I want to add RNN to the machine learning folder. Kindly assign this to me. Thank you.

**Comment by Ishita-Jena** [comment]
I'm going to add a brief introduction, types of rnn, its architecture and working, applications, advantages and disadvantages along with a rnn model built from a scratch.

**Comment by ashitaprasad** [comment]
Thanks for clarifying. This kind of content is widely available and currently not accepted.
