### ISSUE TITLE
Exception handling & error handling is also imp :)

### ISSUE THREAD

**Issue by prasad-chavan1** [animator/learn-python#13]
Exceptions are events that occur during the execution of a program that disrupts the normal flow of instructions 🥇

**Comment by animator** [comment]
@prasad-chavan1 @nagamukesh Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
