### ISSUE TITLE
Group by Functions in Pandas

### ISSUE THREAD

**Issue by AnushkaJMokashi** [animator/learn-python#132]
I would like to add Group By function usage on Data frame with pandas.

Please provide me this task for GSSOC'24.

**Comment by Kazasunitha** [comment]
I want solve this issue and I can add Group by function usage on data as I have good knowledge in  using Pandas library.I request you to assign this task for me under GSSoC'24 and label it.

**Comment by DeepikaMunimadagu** [comment]
Hello I would like to add group by function usage in pandas using examples. Please assign me this task for GSSOC'24

**Comment by AnushkaJMokashi** [comment]
@animator,  Please Review
