### ISSUE TITLE
GUI Tic tac toe game using python

### ISSUE THREAD

**Issue by chaanakyaaM** [animator/learn-python#135]
Hello @animator ,
I want to add a GUI(graphic user interface) TIC TAC TOE game using python.

which will be:
- Easy to play
- User friendly interface
- Introduction to GUI using python
- A mini project

**Comment by chaanakyaaM** [comment]
would you assign it to me?

**Comment by chaanakyaaM** [comment]
let me know if there are any changes to be made,
Thank you.

**Comment by chaanakyaaM** [comment]
Let me know if there are any changes to be made.

**Comment by animator** [comment]
Pick up some other topic. GUI/Tkinter is currently not under the scope of this project.
