### ISSUE TITLE
Adding beginners' practice codes for input and output methods

### ISSUE THREAD

**Issue by Shar-03** [animator/learn-python#137]
As instructed by @animator sir, here is an issue raised regarding adding practice code exercises for different methods of input and output in python so that students can practice the codes to understand the concept. Sir, I request you to assign this task to me. Thankyou.

**Comment by Akshitha28112004** [comment]
Hey I'm good at python and would like to add few interesting questions on input and output methods for beginners so can you please assign me this issue under GSSOC'24?

**Comment by animator** [comment]
We are not accepting any practice coding questions. Pick another topic and raise a new issue.
