### ISSUE TITLE
Using Command Prompt for coding python

### ISSUE THREAD

**Issue by Varshini0703** [animator/learn-python#138]
After the installation of Python, the IDLE version is shown, but the command prompt could also be used to code. CMD is more flexible, and integrated and is more suitable for running scripts. After all, learning basic commands is necessary.

**Comment by Varshini0703** [comment]
I can add a tutorial on how to use the command prompt to code. I'll include pictures and provide a step-by-step tutorial on required commands to get started with coding in cmd. Both Windows and Mac versions would be available.

**Comment by animator** [comment]
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
