### ISSUE TITLE
Python used in different sectors

### ISSUE THREAD

**Issue by Sudiksha18** [animator/learn-python#139]
Python is used in machine learning and in diff sectors with different libraries in python .How the python is used can assign me this task

**Comment by Learner-khushichauhan** [comment]
hi @animator sir, 
can you label this issue I would like to contribute this project please assign it to me under ### GSSOC'24
I have a knowledge about HTML ,CSS and PYTHON . so i do these work best .

**Comment by deekshithapalla** [comment]
I would like to work on this issue sir. Please assign this task o me.

**Comment by animator** [comment]
We have already provided topic outlines in the Contributing Guide.
Kindly follow proper process and raise an issue.
