### ISSUE TITLE
Adding some Real-life based Assessment questions after each chapter in the module.

### ISSUE THREAD

**Issue by Flashl3opard** [animator/learn-python#14]
Hello, I want to add some practice questions and assessments (that will assist the learner by increasing his skills and confidence through problem solving on the topic-of-interest ) after completion of each chapter in the PDF.
Please assign me this issue under GSSoC'24.
Thank you.

**Comment by prajwaldp223** [comment]
hello, i am contributor under GSSoC'24 , and  i would liket o work on this area by adding few real life based examples and assignmenets after each chapter learned

**Comment by Kirti-Pant** [comment]
Hey, I want to work on this issue please assign this issue under GSSoC'24

**Comment by FatemaBaig** [comment]
Hello,
i would like to work on this amazing things to add something new . Assign it to me.

**Comment by animator** [comment]
@Flashl3opard @Kirti-Pant @FatemaBaig @prajwaldp223 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
