### ISSUE TITLE
Adding beginners' practice codes for Control Flow

### ISSUE THREAD

**Issue by Shar-03** [animator/learn-python#140]
As per @animator sir's instructions, here is an issue for adding practice codes for the topic control flow so that newcomers can practice and understand the concept flow statements. I request you sir to assign this issue to me.
Thank you

**Comment by deekshithapalla** [comment]
I would like to work on this issue sir. Please assign this task to me.

**Comment by Akshitha28112004** [comment]
Hey , I am good at python and would like to add few interesting questions for control flow statements so can you please assign me this issue under GSSOC'24?

**Comment by animator** [comment]
We are not accepting any practice coding questions. Pick another topic and raise a new issue.
