### ISSUE TITLE
Mini Project - Rock Paper Scissors Game

### ISSUE THREAD

**Issue by Antiquely3059** [animator/learn-python#142]
Rock Paper Scissors:
Players choose rock, paper, or scissors.
Rock beats scissors, scissors beat paper, paper beats rock.
Outcome determines winner; tie if both choose same.
Randomly generated choice for each game.
User-friendly interface.
Implemented as a GUI game with player and computer choices.

**Comment by hasmithagunda123** [comment]
I want to implement it with best UI. Please assign me

**Comment by prajwaldp223** [comment]
can i work on it?
