### ISSUE TITLE
Adding another section

### ISSUE THREAD

**Issue by MetiUmashri** [animator/learn-python#149]
At the end we can add that commonly asked interview questions list. This kind of helps on how to prepare with the existing resource.
I will make sure that this will more informative. This is a feature addition which will improvise the website. Could you please assign this issue.

**Comment by MetiUmashri** [comment]
could you please respond so that i can start my contribution

**Comment by animator** [comment]
This topic will only be available after all sections are complete. You can pick another topic and open a new issue.
