### ISSUE TITLE
Redesign of the webpage

### ISSUE THREAD

**Issue by ashwin-j-r** [animator/learn-python#153]
Redesign of the webpage such as dropdown in the table of contents so that contents can be arranged properly. And updating the table of contents in the website so that it could be arranged properly , and the users don't have to scroll down, etc. and add some colours to link text etc.
![Screenshot 2024-05-12 162012](https://github.com/animator/learn-python/assets/75122684/e3a29427-6881-408b-a95f-fc9be7fcf0da)

Add colours and dropdown to this also .

I would love to work on this , please assign it to me

**Comment by animator** [comment]
Read the Contributing Guide for topic content ideas and raise an issue.
