### ISSUE TITLE
Adding beginner's friendly Guess the Number game

### ISSUE THREAD

**Issue by StutiRajput07** [animator/learn-python#154]
This is a basic game which provides better understanding of python basics.
In this game  the user selects a range, let’s say User selected a range, i.e., from A to B, where A and B belong to Integer.
Some random integer will be selected by the system and the user has to guess that integer in the minimum number of guesses.

**Comment by bhavyasri9** [comment]
Please assign me this.I want to work on it.

**Comment by Dan1e1B** [comment]
I can also help :)

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
