### ISSUE TITLE
OOPS

### ISSUE THREAD

**Issue by rajan-poudel** [animator/learn-python#156]
As i went through your repo , I found OOPS section was missing . I am a fluent python developer, so i can help add that section , so please provide this issue to me !

**Comment by Akshitha28112004** [comment]
Hey I've learned oops concepts through Java and I'm good at python so can you please assign me this issue?

**Comment by animator** [comment]
Closing as no PR has been raised so far.

**Comment by rajan-poudel** [comment]
@animator Extremely sorry ! My exams were going on and i was unable to do the task i was assigned of.
I am confident enough that i can do this. Could you please reassign me with this task? :)
