### ISSUE TITLE
Adding Operations on Arrays in NumPy

### ISSUE THREAD

**Issue by Yodha-Sudarsi** [animator/learn-python#160]
Hey @animator , I've experience installing NumPy on local systems and using it extensively in my projects. I'm skilled in working with NumPy and would like to contribute by adding **operations on arrays**. Could you assign this task to me?

**Comment by Kazasunitha** [comment]
I want to solve this issue . I have good knowledge of using NumPy module which is used for numerical data manupulation.
Arrays can be created by using np.array() function. We can calculate shape of array  and mathematical operations like np.add(arr1,arr2),np.subtract(arr1,arr2)..etc .So please assign this task for me under GSSoC'24
