### ISSUE TITLE
Add a concept of virtual environments

### ISSUE THREAD

**Issue by ishant9805** [animator/learn-python#165]
Sir, 
In your documentation, you have not mentioned any topic regarding virtual environment which is a must for the people who are learning python as it helps in package management, solves the version conflict problem, etc. Thus, benefitting the new learners to start working on any projects easily. 
Therefore, I would request you(@animator) to assign me this issue.
I will try my best to solve it.
With regards,
Ishant

**Comment by ishant9805** [comment]
Sir, I am a little bit confused as this will be my first contribution in open source world. And, I hope you will help me.
So, coming to the point, the confusion is about where should I add this concept. I think adding a section in starting of mini projects would be better. As, concepts of virtual environments are used while starting a project. Therefore that would be better, and also I have used the default  venv module and uv library for creating virtual environments. And, I felt that uv is a bit faster. Thus, I would also add a guide about using both libraries.

**Comment by animator** [comment]
Add in Advanced Python

**Comment by ishant9805** [comment]
got it
