### ISSUE TITLE
GSSoc'24: Mini Project- Password Generator

### ISSUE THREAD

**Issue by devidutta-learn** [animator/learn-python#166]
I plan to implement it using:

- [x] Random module to generate characters.
- [x] String manipulation functions to create the password.
- [x] User input to determine password length and complexity.

Please let me know if this approach aligns with the project's goals.

**Comment by FatemaBaig** [comment]
Hii,
I would like to work on this part that is password generator.
Please assign it to me under GSSOC-24.

**Comment by animator** [comment]
This issue is no longer under the scope of this project. Pick another topic and raise a new issue.
