### ISSUE TITLE
[ add about pip ]  Installing python modules 

### ISSUE THREAD

**Issue by Yatharth31** [animator/learn-python#17]
Will add about the following under Python Standard library section
- pip
- installing modules via pip
- general issues with pip and solutions
- more suggestion if you have any

Using official documentation and O'Riely Learning Python Edition 4 and Official documentation as reference.
https://docs.python.org/3/installing/index.html#

Please assign me this under GSSOC'24.

**Comment by PilotAxis** [comment]
Hi @Yatharth31  , I am a GSSoC'24 Contributor. I would like to contribute in this, please assign this issue to me. I have a clear understanding of installing modules in Python and I also worked on some modules e.g inbuilt modules/libraries and user added modules. I hope you'll assign this issue to me!

**Comment by somyasaxena01** [comment]
Hello @Yatharth31 , I an a GSSoC'24 Contributor. I do have some understanding of installing modules in Python and I would like to contribute to this issue, I request you to assign it to me.

**Comment by sujanMidatani7** [comment]
assign me this @animator i will do this
