### ISSUE TITLE
Add History of Python and how Python evolved over the years.

### ISSUE THREAD

**Issue by govinddwivedigit** [animator/learn-python#170]
1. Introduction to Python
2. Early Development (1989-1994)
3. Python 1.x (1994-2000)
4. Python 2.x Era (2000-2008)
5. Transition to Python 3.x (2008-2010)
6. Modern Python (2010-present)
7. Community and Ecosystem Growth
8. Recent Developments and Future Outlook

**Comment by govinddwivedigit** [comment]
@animator Can you assign this issue to me ?

**Comment by Ananyagra24** [comment]
I would like to work on this issue. Can you assign this issue to me?

**Comment by animator** [comment]
Read the Contributing Guide for better topic ideas and raise an issue.
