### ISSUE TITLE
Feat : Content based Movie-Recommendation system under Machine Learning 

### ISSUE THREAD

**Issue by shubha987** [animator/learn-python#173]
on the basis of content of TMDB5000 dataset I want to make a movie recommendation system and also using streamlit it can be seen 

@animator please assign me the issue

**Comment by shubha987** [comment]
Hey , I am working on that issue ...now I am doing in details explanation in .md file and also the notebook...

**Comment by animator** [comment]
We are not accepting any notebook.
You can only provide well written markdown.

**Comment by shubha987** [comment]
Ok ..I am writing all the details for this project in markdown
