### ISSUE TITLE
[Add Content] Introduction to Numpy

### ISSUE THREAD

**Issue by PilotAxis** [animator/learn-python#175]
Hey, @animator, I am a GSSoC'24 contributor. I have read the contributing guide in the Contribution.md file. I want to add the content of the **introduction to numpy**. This content idea was mentioned in your guide. Can you please assign the issue to me and label this issue.

Topics covered - Intro to Numpy (What is Numpy [details], how to install numpy, how to use numpy in Python IDLE and on different IDEs)

**Please assign this issue to me.**

**Comment by deekshithapalla** [comment]
I would like to work on this issue. Please assign this task to me.

**Comment by FatemaBaig** [comment]
I would like to work on this part. Please assign it to me under GSSOC-24.

**Comment by PilotAxis** [comment]
Thanks @animator for assigning the issue. I'll try to finish it as soon as possible.
