### ISSUE TITLE
[Add Content] Introduction to Queues

### ISSUE THREAD

**Issue by PilotAxis** [animator/learn-python#176]
Hey @animator, I am a GSSoC'24 Contributor. I would like to contribute to your project by adding content of **Introduction to Queues**. Please assign this issue to me.

### Topics Covered - 
**1. Introduction, 2. What are Queues, 3. Queues important terminology such as (REAR, FRONT, HEAD/TAIL), 4. Real-life Examples of Queues**

**Comment by Akshitha28112004** [comment]
Hey, I am good at Python and would like to add an introduction, operations, and example codes. Can you please assign me this issue under gssoc'24?

**Comment by PilotAxis** [comment]
Thanks @animator for assigning the issue. I'll try to finish it as soon as possible.
