### ISSUE TITLE
Adding a tic-tac-toe game

### ISSUE THREAD

**Issue by DivyanshiSingh00** [animator/learn-python#177]
Adding a tic-tac-toe game in python!!
Please assign it to me!

**Comment by Aditi22Bansal** [comment]
I can make the tic-tac-toe game in Python
Can you please assign this issue to me

**Comment by JanitKumar** [comment]
I can make tic tac toe game please assign it to me

**Comment by FatemaBaig** [comment]
Hi! 
I am interested in this .
I would like to work on this please assign it to me under GSSOC-24.

**Comment by AnshitaSingh123** [comment]
I can do this task. Please assign this task to me.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
