### ISSUE TITLE
Favicon not showing up

### ISSUE THREAD

**Issue by namanomar** [animator/learn-python#181]
![image](https://github.com/animator/learn-python/assets/142042135/84d285f9-716d-44fd-833b-96368714c467)
Image showing that favicon not appearing in website
How I will solve this?
- Design Favicon if not existing 
- Add Favicon

I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by animator** [comment]
Read the Contributing Guide properly.
