### ISSUE TITLE
GSSOC 2024 : Application Tracking System using Gemini Pro.

### ISSUE THREAD

**Issue by VarsaGupta** [animator/learn-python#182]
I would like to develop an ATS (Applicant Tracking System) utilizing Google's Generative AI, particularly the Gemini Pro model, to create the ATS Resume Expert. This web application on Streamlit will serve as a valuable tool for HR professionals and job seekers, aiding in the analysis and alignment of resumes with specific job descriptions.

@animator, Please assign me the issue!!

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.

**Comment by VarsaGupta** [comment]
I would like to add this content under the topic "Python mini project". Can I do so?

**Comment by animator** [comment]
No. Mini Projects should not use external APIs.
