### ISSUE TITLE
Create a Library Management System using Python

### ISSUE THREAD

**Issue by Aditi22Bansal** [animator/learn-python#184]
This project will be coded in Anaconda, Jupyter Notebook, Python pandas with the help of CSV. This code will mainly focus on the basic operations in a library like adding new books in library, issuing and submission of books, and searching books on the basis of their author and book name. Furthermore, the books that are not required will be deleted too.

This program will have six main functions:-

Adding new book
Issuing a book
Submitting issued book
Deleting a record
Searching a specific record
Displaying the records

**Comment by Akshitha28112004** [comment]
Hey I'm good at python . You can check my profile I've already done Restaurant management system but that was under databases . Can you please assign me this issue under GSSOC'24 ?
