### ISSUE TITLE
Introduction to Decision Trees 

### ISSUE THREAD

**Issue by Jaya-Prakash-17** [animator/learn-python#189]
I would like to add content on classification using Decision Trees as it is fundamental yet Powerful and one of the most used ML models. I would like to add a brief introduction and then implement a Decision Tree on a basic data set to help beginners know how Decision Trees work.

**Comment by Jaya-Prakash-17** [comment]
@animator Sir,I am a contributor @GsSOC24, I have raised this issue so that I can add some valuable information for beginners who would visit this repo.
So, kindly accept my request. I would like to work on this issue.

**Comment by Jaya-Prakash-17** [comment]
Thanks @animator for assigning this issue to me.

before I start working on this issue, I have one doubt which I want to clarify.
am  i supposed to create  new folder and put a .ipynb in it or am i supposed to just edit the README.md file of this repository?

I'm sorry but i couldn't find clear instructions on what should be done.
waiting for your humble guidance

**Comment by animator** [comment]
Contributing guide clearly describes what has to be done.

**Comment by Jaya-Prakash-17** [comment]
> Contributing guide clearly describes what has to be done.

Yeah sure! I'll go through it it
