### ISSUE TITLE
Adding Beginner's practice codes.

### ISSUE THREAD

**Issue by ANSHIKA1220** [animator/learn-python#19]
The following codes can be added as a part of basic programming questions:
1) Fibonacci Series
2) Printing a list of prime numbers
3) Factorial Computation
4) Reverse Fibonacci 
5) Bubble sort 

Please assign me the task to do the same under GSSOC'24

**Comment by Shar-03** [comment]
Hi, greetings of the day. I am a contributor at GirlScript Summer of Code. I find your project initiative to be very interesting and would like to contribute to it. I am a pre final year student currently pursuing my B.Tech degree in Computer Science with a specializaton in Artificial Intelligence and Machine Learning. As part of my learning, I have worked quite a lot with Python Language and I think I could suggest a few beginner friendly python codes to make this platform open to beginners. I would be very grateful if you could assign this issue to me. 

Regards,
Sharvari Wakhare

**Comment by akshatsharma2407** [comment]
I'm the perfect fit for this task because I'm bursting with excitement to uplift beginners on their Python journey. My approach? It's all about infusing simplicity with creativity, making sure every learner feels empowered and engaged. Let's team up and ignite the passion for Python in countless new enthusiasts together! so please assign me this task.

**Comment by VijaySamant4368** [comment]
Hi everyone,

I'm excited about the idea of adding beginner's practice codes to the project! I believe this would be incredibly beneficial for newcomers to Python and programming in general. To help kickstart this initiative, I've compiled a list of 11 beginner-friendly coding challenges below:

1. **Fibonacci Sequence:** Generate the Fibonacci sequence up to a specified number.
   
   ```python
   # Example input: n = 7
   # Expected output: [0, 1, 1, 2, 3, 5, 8]
   ```

2. **Factorial:** Calculate the factorial of a given number.
   
   ```python
   # Example input: n = 5
   # Expected output: 120
   ```

3. **Sum of Digits:** Calculate the sum of digits in a number.
   
   ```python
   # Example input: n = 1234
   # Expected output: 10
   ```

4 **Palindrome Checker:** Check if a given string is a palindrome.
   
   ```python
   # Example input: "radar"
   # Expected output: True
   ```

5. **Reverse a String:** Reverse a given string.
   
   ```python
   # Example input: "hello"
   # Expected output: "olleh"
   ```

6. **Check for Prime Number:** Determine if a given number is prime.
   
   ```python
   # Example input: n = 13
   # Expected output: True
   ```

7. **Count Vowels:** Count the number of vowels in a given string.
   
   ```python
   # Example input: "hello"
   # Expected output: 2
   ```

8. **Remove Duplicates:** Remove duplicates from a list.
   
   ```python
   # Example input: [1, 2, 2, 3, 4, 4, 5]
   # Expected output: [1, 2, 3, 4, 5]
   ```

9. **Calculate Power:** Calculate the power of a number without using the /*/* operator.
   
    ```python
    # Example input: base = 2, exponent = 3
    # Expected output: 8
    ```

10. **Find Largest Element:** Find the largest element in a list.
    
    ```python
    # Example input: [3, 7, 2, 8, 4]
    # Expected output: 8
    ```

11. **Binary to Decimal Conversion:** Convert a binary number to decimal. using basic arithmetic operations.
    
    ```python
    # Example input: "1010"
    # Expected output: 10
    ```

I believe these challenges will help beginners get started with Python programming.

**Comment by VijaySamant4368** [comment]
---
Hi everyone,

I'm excited about the idea of adding beginner's practice codes to the project! I believe this would be incredibly beneficial for newcomers to Python and programming in general. To help kickstart this initiative, I've compiled a list of 11 beginner-friendly coding challenges below:

1. **Fibonacci Sequence:** Generate the Fibonacci sequence up to a specified number.
   
   ```python
   # Example input: n = 7
   # Expected output: [0, 1, 1, 2, 3, 5, 8]
   ```

2. **Factorial:** Calculate the factorial of a given number.
   
   ```python
   # Example input: n = 5
   # Expected output: 120
   ```

3. **Sum of Digits:** Calculate the sum of digits in a number.
   
   ```python
   # Example input: n = 1234
   # Expected output: 10
   ```

4. **Palindrome Checker:** Check if a given string is a palindrome.
   
   ```python
   # Example input: "radar"
   # Expected output: True
   ```

5. **Reverse a String:** Reverse a given string.
   
   ```python
   # Example input: "hello"
   # Expected output: "olleh"
   ```

6. **Check for Prime Number:** Determine if a given number is prime.
   
   ```python
   # Example input: n = 13
   # Expected output: True
   ```

7. **Count Vowels:** Count the number of vowels in a given string.
   
   ```python
   # Example input: "hello"
   # Expected output: 2
   ```

8. **Remove Duplicates:** Remove duplicates from a list.
   
   ```python
   # Example input: [1, 2, 2, 3, 4, 4, 5]
   # Expected output: [1, 2, 3, 4, 5]
   ```

9. **Calculate Power:** Calculate the power of a number without using the ** operator.
   
    ```python
    # Example input: base = 2, exponent = 3
    # Expected output: 8
    ```

10. **Find Largest Element:** Find the largest element in a list.
    
    ```python
    # Example input: [3, 7, 2, 8, 4]
    # Expected output: 8
    ```

11. **Binary to Decimal Conversion:** Convert a binary number to decimal. using basic arithmetic operations.
    
    ```python
    # Example input: "1010"
    # Expected output: 10
    ```

I believe these challenges will help beginners get started with Python programming.
---

**Comment by animator** [comment]
@Shar-03 @VijaySamant4368 @ANSHIKA1220 @akshatsharma2407 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
