### ISSUE TITLE
[ADD CONTENT] GSSOC'24 : Data Structures & Algorithms - Add about SORTING ALGORITHMNS

### ISSUE THREAD

**Issue by Yatharth31** [animator/learn-python#190]
Hey @animator , I am a GSSoC'24 Contributor. I would like to contribute to your project by adding content about various Sorting algorithms. Please assign this issue to me.

Topics Covered -
1. Bubble Sort, 2. Merge Sort, 3. Quick Sort, 4. Selection Sort.

**Comment by arun0r7** [comment]
Hi. @animator I'm Arun.R. A GSSoC'24 Contributor. I would like to contribute my coding knowledge to your projects by adding contents and codes about DSA- Sorting Algorithms. I've experience in Python coding and would like to contribute here. Kindly assign this to me.
I would like to cover the following topics here:
1.Bubble Sort.
2.Selection Sort.
3.Insertion Sort.
4.Heap Sort.
5.Quick Sort.
Can you please label the following project?

**Comment by Akshitha28112004** [comment]
Hi. I am good at Python. I would like to include bubble, merge, insertion, selection, quick, and heap sort. Can you assign me this issue under gssoc'24?
