### ISSUE TITLE
[Add Content] - Data Structure & Algorithms - Add about Time and Space Complexity

### ISSUE THREAD

**Issue by Yatharth31** [animator/learn-python#191]
Hey @animator , I am a GSSoC'24 Contributor. I would like to contribute to your project by adding content about Time and Space complexity analysis of algorithms. Please assign this issue to me.

Topics Covered -
1. Big Oh, 2. Big Omega, 3. Big Theta, 4. Best Case, Worst Case, Average Case, 5. Time Complexity, 6. Space Complexity.

**Comment by Akshitha28112004** [comment]
Hey, I am good at Python. Can you assign me this issue under gssoc'24?

**Comment by Yatharth31** [comment]
Am i allowed to add images of graphs of BigOh and other functions, also comparison of various time complexities w.r.to. input size. Should I create a new folder inside ds-algo name images? Or there is no need for this?

**Comment by animator** [comment]
new folder inside ds-algo name images
The images must not be copied from somewhere else.
