### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by sanjay-kv** [animator/learn-python#2]
In GSSoC'24, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue. 👍

**Comment by MahraibFatima** [comment]
I recently made a Jarvis in python using py libraries. I want to add Jarvis project.
kindly guide me little bit. Am I have to just add code to your repo in .py extension or what have to do?
and tell your requirements if you have any.
Also, Assign this issue to me as well so I'll start my work regarding this.

**Comment by Ishita-Jena** [comment]
I want to add data structures such as linked list, stack, queue, etc. to this project. Please assign this issue to me so I can start working on it.

**Comment by krish-san** [comment]
Hello, I've noticed that you already have adequate topics on your repository. I would like to add more about python modules (as like widely used NumPy, Pandas , plotly , Scikit learn, Matplotlib) letting learners know how these python modules helps widely in the filed of data science . Also I'd love to add on about python's Pygame features. As someone who's very familiar with python for several years, i'd love to contribute to this issue and add more sections which you'd like me to work on. Please assign me this issue under GSSoc'24. 
Thankyou!

**Comment by Flashl3opard** [comment]
Hello, I want to add  some practice questions and assessments (that will assist the learner by increasing his skills and confidence through problem solving on the topic-of-interest ) after completion of each chapter in the PDF.
Please assign me this issue under GSSoC'24.
Thank you.

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by miss-panchal** [comment]
hello , i would like to add some function in this like i haven't seen lamda function in this which is also a important topic. 
and can give overview in this like what is numpy and what it is used for rather than having numpy or pandas in this.

**Comment by manuu16** [comment]
Hello sir! I'd like to propose an improvement to the 'Errors and Exception Handling' section by adding more details on two key concepts: Exception Chaining and User-Defined Exceptions. I'm happy to contribute by creating content that gives a clear understanding of the topic with code examples. Could you please assign me this task to me?

**Comment by animator** [comment]
@MahraibFatima @Ishita-Jena @krish-san @Flashl3opard @hasmithagunda123 @miss-panchal @manuu16 
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
