### ISSUE TITLE
helping people contribute adding steps to CONTRIBUTING.md

### ISSUE THREAD

**Issue by riteshpushkar** [animator/learn-python#205]
I will be adding all the steps in detail like
fork
clone
branch change
add
commit
push
how to create pr
I'll be explaining everything in details to contibutors new to open source
pls assign me this under label gssoc24

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
