### ISSUE TITLE
different libraries available by python

### ISSUE THREAD

**Issue by shreyasadhasivam** [animator/learn-python#208]
I'm a GsSoc contributor. I would like to add all the libraries that are available in python and their uses. some type of a glossary.

please assign this issue to me.

**Comment by Akshitha28112004** [comment]
Hey, I am good at python so can you please assign me this issue under GSSOC'24?

**Comment by animator** [comment]
Went through the PR. This section is very vague and not that helpful currently. Please pick some other issue.

**Comment by shreyasadhasivam** [comment]
I will be adding more content. this was just the first part. Please assign this issue to me again and I'll submit the entire thing together. @animator
