### ISSUE TITLE
Adding search bar

### ISSUE THREAD

**Issue by ASLSwetha** [animator/learn-python#21]
adding a search bar at the top can let the learner search for a particular topic. I will help adding this new feature.

**Comment by Riya922003** [comment]
can I work on this issue I am a gssoc contributor

**Comment by animator** [comment]
@ASLSwetha @Riya922003 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
