### ISSUE TITLE
Add Content: Importing and exporting the data in pandas

### ISSUE THREAD

**Issue by kRiShNa-429407** [animator/learn-python#211]
Please assign me this content

**Comment by Sayeda-fatima** [comment]
Hi, I'm a GSSoC'24 contributor. Please assign me this issue

**Comment by DG492003** [comment]
Hi, I'm a contributor with 1 year of experience in Python, and I'm interested in working on this problem.

**Comment by Kazasunitha** [comment]
I want To solve this issue. I have good knowledge at using Pandas Library.We can import the data by using read_csv, read_excel
,read_sql, read_json like this functions. We can export the data in python by using to_csv, to_excel ...etc . So please assign this task to me under GCCoS'24 and label it

**Comment by kRiShNa-429407** [comment]
Please check my pull request

**Comment by DG492003** [comment]
I'm not a repo owner

**Comment by kRiShNa-429407** [comment]
I am requesting to ankit mahato sir

**Comment by kRiShNa-429407** [comment]
Sir my content is ready and also added 
Please approve my current PR so that i can raise a PR for this.

Thank you

**Comment by kRiShNa-429407** [comment]
please re-assign it
