### ISSUE TITLE
Mini Project- Weather Condition(based on location)

### ISSUE THREAD

**Issue by Anshika14528** [animator/learn-python#214]
1. Allow users to input a location  for which they want to check the weather.

2. Use a weather API (such as OpenWeatherMap,  WeatherAPI) to fetch current weather conditions for the specified location.

3. Show the current temperature, weather description (e.g., sunny, cloudy, rainy), humidity, wind speed, and any other relevant data.

 I agree to follow this project's Code of Conduct
 I'm a GSSoC'24 contributor
 I want to work on this issue

**Comment by merciajeno** [comment]
I am GSSOC'24 contributor and have worked with weather API's using spring boot. I have the ability to tackle this issue. Please assign this task to me.
