### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [animator/learn-python#219]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet(using Github Bots) users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

**Comment by animator** [comment]
Read the Contributing Guide properly.
