### ISSUE TITLE
Neural Networks: Introduction to AI

### ISSUE THREAD

**Issue by iABn0rma1** [animator/learn-python#226]
I propose adding the implementation of Neural Networks from scratch, using Numpy and Pandas. Focussing on how the model architecture trains on input data and self-improves based on the error rate.

**Comment by Vis1hal** [comment]
can you explain it in more details?

**Comment by iABn0rma1** [comment]
> can you explain it in more details? 
@Vis1hal 

For forward pass, the user gives the input values (x_i). Each input is multiplied with a randomly assigned weight (w_i), representing the importance of input features. Higher weights indicate greater importance. Then, the sum of these weighted inputs is calculated.
Next, an activation function is applied to introduce non-linearity by capturing complex patterns. The result determines whether a neuron will "fire", passing its output as input for the neurons in the succeeding layers. Given by the equation:
```math
y =  f(\sum_{i=1}^n w_i x_i )
```
With the output value, the backward pass is introduced to update weights based on the gradient of error, given by $`∂E/∂w_i`$. There are numerous ways to calculate the error rate, depending on the use case. The most known is Root Mean Squared Error, RMSE = $`\sqrt{(1/n) * Σ(y_i - ŷ_i)^2}`$.
 
A simple illustration:
![0-1](https://github.com/animator/learn-python/assets/75512370/c1fb25a2-fa99-492d-8123-076e6866edd1)
