### ISSUE TITLE
GenAI Based Content

### ISSUE THREAD

**Issue by KomalSiddharth** [animator/learn-python#228]
i would like to provide genai related content in an easy and understandable format
I can also content and project ideas based on above and related fields
plz do provide me this golden opportunity to work on theses tasks.

**Comment by DineshkumarS05** [comment]
I have done a project based on this known as smart ai tutor. where i used Mistral model to make the content easy when the student requested. I have xperience in this. so I request you to assign the issue for me under GSSoC'24. Thank you

**Comment by animator** [comment]
GenAI related content goes here - https://github.com/foss42/awesome-generative-ai-apis
