### ISSUE TITLE
Lambda Function

### ISSUE THREAD

**Issue by paneer24** [animator/learn-python#229]
I would like to provide a brief overview of what Lambda functions are how to write them

**Comment by Kazasunitha** [comment]
Lambda functions in Python are also Known as Anonymous function. Anonymous means name less functions. Th e syntax for the lambda function is: lambda argument : expression
example:
y=lambda a : a+10
print(y(10))
output:
20
explanation : The name less function is assigned to "y" varaible so 'Y' is the name of the function here and "a" is the argument or parameter that is passed to function. The left side of ":" should have the arguments of the functions and right side should have the expression to be evaluated when the function is called.

**Comment by AmruthaPariprolu** [comment]
hey @animator 
i would like to provide info regarding lambda functions could you pls assign me this issue
