### ISSUE TITLE
Basic Python Exercises for Beginners

### ISSUE THREAD

**Issue by akhundubedullah** [animator/learn-python#23]
If this issue is assigned to me, I will create a curated collection of beginner-friendly Python tasks that focus on reinforcing fundamental concepts and building practical programming skills. Each exercise will include the following:

Clear Problem Statement: A concise description of the task to be completed.

Sample Solutions: One or more example solutions demonstrating different approaches or levels of complexity.

Explanations: Detailed explanations of the code, including the reasoning behind the chosen solution and key concepts demonstrated.

Please assign me this issue with the GSSOC'24 tag.

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of writing the BASIC PYTHON EXERCISES FOR BEGINNERS section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by VijaySamant4368** [comment]
Hi everyone,

I'm excited to propose a set of basic exercises tailored for Python beginners. These exercises will cover fundamental concepts to help newcomers gain confidence in Python programming.

**Proposed Exercises:**
1. **Variables and Data Types:** Implement exercises to practice using variables, integers, floats, strings, and basic operations.
2. **Control Flow:** Include exercises on conditional statements (if, elif, else) and loops (for, while).
3. **Functions:** Provide exercises to understand how to define and call functions, as well as pass arguments.

**Expected Outcome:**
- Participants will gain hands-on experience with essential Python concepts.
- Increased confidence in writing simple Python programs.
- Solid foundation for more advanced topics.

I'm looking forward to working on this project and contributing to the Python learning resources.

**Comment by Sansrita** [comment]
Hi @animator , I would like to contribute on this project, as a Python Developer I will add level wise and module wise Python exercise for beginners so that they could practice module wise and level up.

**Comment by sleathblack007** [comment]
Hi @animator , I would like to contribute on this project, as a Python Developer I will add level wise and module wise Python exercise for beginners so that they could practice module wise and level up.

**Comment by animator** [comment]
@Sansrita @VijaySamant4368 @akshatsharma2407 @akhundubedullah @sleathblack007 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
