### ISSUE TITLE
Add the concept of classes, creating objects and inheritence of classes

### ISSUE THREAD

**Issue by Kazasunitha** [animator/learn-python#230]
Description :  One Should add the use of object oriented programming in python , Creation of classes and object creation.
Should explain the concepts of polymorphism, inheritence ,Compile and Run time binding, Encapsulation,Method overloading and method Overiding.

**Comment by Kazasunitha** [comment]
Please assign this task for me under GCCoS'24 I can solve this issue and label it

**Comment by animator** [comment]
Closing as no PR has been raised so far.

**Comment by Kazasunitha** [comment]
could you plz re-assign this I have in work.

**Comment by animator** [comment]
ok

**Comment by Kazasunitha** [comment]
could you plz assign me also for that. So I can improve it
