### ISSUE TITLE
Using Python Codes for making games

### ISSUE THREAD

**Issue by ShreyaMathur19** [animator/learn-python#231]
Apart from theory and practicing some serious problem their should be content that would help user and introduce them how python can be used for making games using libraries or other simple syntaxes. I want to contribute in this project under GSSoC'24 as I am also learning python since last 4 years, I believe I can make a efficient contribution in this.

**Comment by animator** [comment]
Read the Contributing Guide properly and raise a valid issue.
Be more specific.
