### ISSUE TITLE
Installing Python in linux os

### ISSUE THREAD

**Issue by m-alam13** [animator/learn-python#233]
The Python installation process is only offered for Windows and macOS . I can add python installation procedure in linux os if you assign me.

**Comment by ShubhiGupta20** [comment]
Please assign the Label.
I would like to work on this issue, please assign this to me.

**Comment by m-alam13** [comment]
@ShubhiGupta20 sorry to say.It is **linux** not **linus**.I am using Linux OS since 2020.So I can handle it better than you.
