### ISSUE TITLE
Mini Project: Adding a Word Guessing Game With Lives

### ISSUE THREAD

**Issue by Subhoshri** [animator/learn-python#234]
I want to create a mini-game where one has to guess the word from the number of blank spaces given. There will be three lives for one word, and failing to guess within those three lives ends the game.
This game is like hangman and is simple yet creative and I believe that it will be a good addition to this project.

Please assign me this issue!

**Comment by merciajeno** [comment]
Hello , I have the experience of creating hangman, a game similar to this. Can you assign this task to me?

**Comment by Subhoshri** [comment]
Hey @merciajeno, I have already created the mini-game for this. If you want, we can collaborate on any other issue.

**Comment by merciajeno** [comment]
That would be great, thank you!

**Comment by animator** [comment]
Feedback provided in PR.
