### ISSUE TITLE
[ADD CONTENT] GSSOC'24 : DSA-Searching algorithms 

### ISSUE THREAD

**Issue by kavyaPerepu19** [animator/learn-python#239]
Hey @animator  , I am a GSSoC'24 Contributor. I would like to contribute to your project by adding content about Searching algorithms in python. Please assign this issue to me.
Topics covered:
1)Linear Search
2)Binary Search

**Comment by MrCodYrohit** [comment]
@animator Please assign this issue to me, I would like to work o  it.
