### ISSUE TITLE
Adding Content about Anaconda Navigator and Jupyter Notebook

### ISSUE THREAD

**Issue by PilotAxis** [animator/learn-python#24]
I would like to add content about different types platforms where Python can be incredibly fun to use. Some of them such as Spyder IDE, Jupyter Notebook, PyCharm etc. I can add details about their installation, uses, running applications locally on different operating systems such as Windows, MacOS and Linux. I can also add details about using Jupyter Notebook. This can be very interesting for users who are seeking to take guide in the field of Data Science. 

@animator I hope you'll assign this issue to me...

**Comment by akshatsharma2407** [comment]
With a passion for exploration and a knack for uncovering the intricacies of tools like Anaconda Navigator and Jupyter Notebook,syper,VS-code,google-colab , replit etc .., I'm poised to infuse the content with enthusiasm and clarity. Let's embark on this journey together, crafting engaging insights that make learning an inspiring adventure!

**Comment by animator** [comment]
@PilotAxis @akshatsharma2407 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
