### ISSUE TITLE
[ADD CONTENT] GSSOC'24: reduce(),map(),filter() methods

### ISSUE THREAD

**Issue by kavyaPerepu19** [animator/learn-python#242]
Hey @animator , I am a GSSoC'24 Contributor. I would like to contribute to your project by adding content about methods like 
reduce(),map(),filter().

**Comment by kavyaPerepu19** [comment]
Please kindly assign me this issue under GSSOC'24.

**Comment by animator** [comment]
Closing as no PR has been raised so far.
