### ISSUE TITLE
Feature: Virtual Environment

### ISSUE THREAD

**Issue by aargeee** [animator/learn-python#25]
I'd like to propose a new section in the book concerning about Virtual Environments.

I'd like to structure the code as such
1. Global Environments - explain about what the global environment means and how to distinguish it from a virtual environment
2. Creating Virtual Environments - using `virtualenv` or `venv`
3. Using virtual environments - switching between virtual environments, need of requirements file.
4. Preface to poetry - A simple introduction to poetry and it's features with action cues to direct readers to the right documentation if they fancy further reading.

**Comment by aargeee** [comment]
I will be glad to explain the above mentioned topics. @animator, please assign this issue to me.

**Comment by snehatungana** [comment]
I'd like to work on this issue for GSSoC 2024. Kindly assign this issue to me.

**Comment by animator** [comment]
@aargeee @snehatungana Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
