### ISSUE TITLE
Sorting algorithms 

### ISSUE THREAD

**Issue by Harish-2003** [animator/learn-python#253]
Willing to add all sorting algorithms such as selection, insertion,merge and lot other sorting algorithms

**Comment by AmruthaPariprolu** [comment]
hey
i would like to explain about 
1)bubble sort
2)selection sort
3)insertion sort
4)merge sort
5)heap sort
6)quick sort
and their time complexities
could you pls assign me with this issue under GSSOC'24

**Comment by HardikTripathi04** [comment]
I would like to add sorting algorithms and their code with explanation and dry running them . Assign me under GSSOC'24

**Comment by lakshay-111** [comment]
@animator I will be adding codes for all the sorting algorithm like bubble sort, insertion sort, merge sort, quick sort ,selection sort and heap sort with their simplest code and their code with least time complexity . Will also add time complexity of each sort.
So please assign it to me.
