### ISSUE TITLE
Designing the website & adding new features

### ISSUE THREAD

**Issue by Dishika18** [animator/learn-python#26]
I can make this website more insightful and interactive and also add some feature such as adding copy feature in the code snippet and many more. 
Please assign this issue to me under GSSoC'24.

**Comment by aryasd29** [comment]
I can enrich this website by making it more engaging and informative. Additionally, I'll incorporate practical features like enabling users to easily duplicate code snippets. Kindly assign this task to me for GSSoC'24.

**Comment by MehtabAsHellic** [comment]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by animator** [comment]
@MehtabAsHellic @aryasd29 @Dishika18 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.

**Comment by MehtabAsHellic** [comment]
sure
