### ISSUE TITLE
Adding Rock  Paper Scissors Game

### ISSUE THREAD

**Issue by Syed0206** [animator/learn-python#265]
I would like to add  Rock  Paper Scissors Game @animator can you please assign me this issue under GSSOC'24

**Comment by tejaswi-c** [comment]
Hello,Iam tejaswi.
I am GSSoC'24 contributor. I love to work on this issue.
Kindly assign me the issue.

**Comment by AnshitaSingh123** [comment]
I would like to work on this. Please assign this task to me.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
