### ISSUE TITLE
GSSOC'24 - Mini project- Number guesser

### ISSUE THREAD

**Issue by poorvi1910** [animator/learn-python#266]
A random number is generated and goal of player is to guess the number before number of lives  run out. I would like to be assigned this issue under gssoc

**Comment by poorvi1910** [comment]
Please assign this issue to me

**Comment by poorvi1910** [comment]
@animator I am new to open source. Which folder do i add the code to?

**Comment by Debargha-Saha** [comment]
Hi @animator ,
I would like to solve this number guesser problem having a strong foundation in basic programming I would like to solve this issue.
Please assign the issue to me

**Comment by akshitajaiswal2908** [comment]
A random number is generated and goal of player is to guess the number before number of lives run out. I would like to be assigned this issue under gssoc
