### ISSUE TITLE
 I would like to add text based slot machine game , it will be a mini project  developed by Python . Please assign me this task under GSSOC'2024

### ISSUE THREAD

**Issue by technicalkuldeep** [animator/learn-python#267]
**- The user starts by entering a deposit amount.
- The user then chooses how many lines they want to bet on (1, 2, or 3) and how much they want to bet per line.
- The program generates a random slot machine result.
- The user wins money if they get matching symbols on their bet lines.
- The program keeps track of the user's balance and allows them to keep playing until they run out of money or quit.**

**Comment by technicalkuldeep** [comment]
@animator Please assign me this under GSSOC 2024

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
