### ISSUE TITLE
Fix internal links styling in 'learn-python' web interface

### ISSUE THREAD

**Issue by VijaySamant4368** [animator/learn-python#27]
Hi there,

I noticed an issue regarding the behavior of internal links in the 'learn-python' web interface. It seems like the links are displaying differently from the desired behavior. The following behavior is occurring:

1. The font-color of the links is the same as that of the rest of the document.
2. The underlined links are being normal styled when the curser hover over them.
I have attached the following image regarding the issue:

Light Mode
![Screenshot 2024-05-11 100528](https://github.com/animator/learn-python/assets/145102345/78492f34-b831-4015-b9d9-ded1f9a47c53)

Dark Mode:
![Screenshot 2024-05-11 101950](https://github.com/animator/learn-python/assets/145102345/c6946b3b-df81-412e-9fbc-850ea1947b25)

I suggest that:
1. By default the color of the hyperlinks be blue, and when we hover over them, it becomes the same color as the rest of the text.
2. The hyperlinks be underlined, only when the cursor hover over them
Like in this image:

Light Mode:
![Screenshot 2024-05-11 101913](https://github.com/animator/learn-python/assets/145102345/3cc61aab-3714-44eb-9820-147c9b96b356)

Daek Mode:
![Screenshot 2024-05-11 101937](https://github.com/animator/learn-python/assets/145102345/2aecfd44-e7df-43a3-a5b0-e02a2098332d)

**Note:**
---
In all the four Screenshot, the cursor was over "Introduction to Programming Languages"
I left the color of hyperlinks in the side menu as it is, but I can surely change it, if you deem so.
---

Since the issue can now be addressed by me, could you please assign me this issue under GSSoC? If there are any further changes required or if you need additional information, please feel free to let me know. I'm here to help!

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
