### ISSUE TITLE
Mini Project: Currency Converter

### ISSUE THREAD

**Issue by Anshika14528** [animator/learn-python#273]
Create a simple user interface (UI) where users can input the amount of money they want to convert, select the currency they are converting from, and choose the currency they want to convert to.

I agree to follow this project's Code of Conduct
 I'm a GSSoC'24 contributor
 I want to work on this issue

**Comment by animator** [comment]
From where will you get the conversion rate?

**Comment by arun0r7** [comment]
Hi. I'm Arun.R , GSSoC'24 contributor. I would like to work on this project. Kindly assign this to me.

**Comment by arun0r7** [comment]
Hi. Can you please label this and assign to me?

**Comment by animator** [comment]
It won't be very useful.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
