### ISSUE TITLE
GSSOC' 24   A turn-based dice game for 2-5 players where the goal is to be the first to reach 60 points, avoiding rolling a 1 which ends the turn and forfeits the turn's points.

### ISSUE THREAD

**Issue by technicalkuldeep** [animator/learn-python#277]
A turn-based dice game for 2-5 players where the goal is to be the first to reach 60 points, avoiding rolling a 1 which ends the turn and forfeits the turn's points. all using python 
I have good experience in python so kindly assign me this game .

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
