### ISSUE TITLE
ADD CONTENT: API development

### ISSUE THREAD

**Issue by ramsatyasai** [animator/learn-python#279]
want to add the detailed explanation of status codes 
 - list of status codes 
 - detailed explanation about the status code
 - recommended changes to resolve

**Comment by ananyabansal16** [comment]
I can add detailed explanation of status codes. 
I can work on this issue, you can assign this to me.

**Comment by animator** [comment]
Kindly choose a useful section from the provided topic outlines in the Contributing Guide.
Without practical use currently this addition will not add any value.
