### ISSUE TITLE
Concept of Slicing, and addition to Try....catch block(Error Handling)

### ISSUE THREAD

**Issue by Sagarika-Dubey** [animator/learn-python#28]
We can add about slicing concept under List topic, and also describe that on which data structs allows slicing( eg. only list, string and tuple allows slicing where as sets do not).
We can also add details abut try....catch(error handling) block as its an important concept for getting outputs with less errors

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
