### ISSUE TITLE
pong game using python 

### ISSUE THREAD

**Issue by Pranshu-jais** [animator/learn-python#286]
I would like to add   pong game developed by Python as a mini project . Please assign me this task under GSSOC'2024 with appropriate level (1/2/3)

**Comment by brobengali** [comment]
I would like to add pong game developed by Python as a mini project . Please assign me this task under GSSOC'2024 with appropriate level (1/2/3)

**Comment by ananyabansal16** [comment]
I can add a pong game in python, you can assign this task to me.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
