### ISSUE TITLE
Add new section for requests library

### ISSUE THREAD

**Issue by Programmer-Arvind** [animator/learn-python#29]
I'm writing to suggest a valuable addition to this excellent open-source Python book: a section dedicated to the ```requests``` library.
The ```requests``` library is a powerful and versatile tool for making HTTP requests in Python, simplifying web interactions and data retrieval from web APIs. Its inclusion would significantly enhance the book's coverage of web development and data manipulation capabilities.
I wish to cover the following concepts of the ```requests``` library:
- **Introduction** to ```requests``` library and how to install it using pip.
- **Making GET Requests**: Demonstrate fetching data from web servers using basic GET requests.
- **Handling Responses**: Show how to extract data from the response object, including status codes, headers, and content.
- **Authentication**: Discuss basic authentication techniques for web APIs.
- **Error Handling**: Guide users on handling potential errors and exceptions during requests.
- If required I can even explain about how to handle responses received as a JSON object using the ```json``` standard library.

I am a GSSoC'24 contributor. Kindly assign me this issue and It'll make a great addition to the book and encourage learners to interact with APIs and build amazing new projects for the tech community.

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.

**Comment by Programmer-Arvind** [comment]
@animator Please re open this issue. I'll start working on it now.
