### ISSUE TITLE
Mini Project - Decimal to Binary Converter

### ISSUE THREAD

**Issue by Ananyagra24** [animator/learn-python#292]
To make a program which takes decimal number as input from the user and returns binary equivalent of it.

**Comment by Ananyagra24** [comment]
I would like to work on this issue. Please assign me this issue under GSSOC'24.

**Comment by muskan191103** [comment]
I would like to contribute for this issue
Can you please assign me this issue under GSSOC'24

**Comment by animator** [comment]
Not a useful mini project idea.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
