### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by sanjay-kv** [animator/learn-python#3]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by Aryan-Chharia** [comment]
Hi, I am a contributor in GSSoC'24. I want to work on this issue and add a code of Conduct. Can you assign this issue to me ?

**Comment by SohaFarhana** [comment]
Helloo
I am a contributor of Girl Script 2024 
I would like to work on this area

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by Priyanshu2631** [comment]
Hii, I m a contributor in GSSOC'24, please assign this issue to me, I have prior idea on documenting the Code of Conduct in previous contributions
