### ISSUE TITLE
Introduction to ASCII values 

### ISSUE THREAD

**Issue by keerthi-ganiger** [animator/learn-python#30]
I feel like we should include the concept of ASCII values so that learners can get the difference between "apple" and "Apple" or other examples of similar kind.

**Comment by vsmp47** [comment]
Adding ASCII values would help learners understand how computers represent letters, numbers, and symbols. This knowledge helps them work with text more effectively, like checking if a letter is uppercase or lowercase, or converting between them. I would like to contribute to this issue !

**Comment by SaiSruthisri** [comment]
Hello @animator 
Iam an contributer under GSSOC'24.
Would be glad to have the chance to contribute on this issue under GSSOC'24
> Ascii values are very helpful in compettive programming aspect.
   (I personally used ascii values many times in cp)
> If a person is directly starting to learn first coding language getting introduced to a 
    ascii values  is important.
> I would like to work on this issue by clearly explaining 
         WHY (why is ascii there) ,
         HOW (how it is helpful & used ).aspects.
 
Iam open to the feedback on any changes required.And kindly label the issue under gssoc (1/2/3) .
Thank you!

**Comment by mubinasyed28** [comment]
I have a deep understanding of the topic and would love to contribute to it. Can you please assign the issue to me under GSSoc'24?

**Comment by animator** [comment]
@vsmp47 @mubinasyed28 @SaiSruthisri @keerthi-ganiger Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
