### ISSUE TITLE
Addition of Regression 

### ISSUE THREAD

**Issue by Yogeshkarma** [animator/learn-python#300]
Implementation of Following topics

1. Introduction to Regression
2. Types of Regression
3. Assumptions of Linear Regression
4. Regression Error Metrics in Python

**Comment by Yogeshkarma** [comment]
please add it under gssoc 2024

**Comment by akshitajaiswal2908** [comment]
Implementation of Following topics

Introduction to Regression
Types of Regression
Assumptions of Linear Regression
Regression Error Metrics in Python
#gssoc24
