### ISSUE TITLE
  GSSOC'24 : NumPy Quick Reference Guide

### ISSUE THREAD

**Issue by SkSadaf** [animator/learn-python#301]
As a participant in GSSOC'24, I propose to contribute a NumPy Quick Reference Guide to the this project. This will serve as a guide for users, summarizing common operations, functions, and best practices when working with NumPy arrays.
The Guide will cover essential topics such as array creation, basic operations, indexing and slicing, array functions, linear algebra, statistical functions, and saving/loading arrays. Each section will include concise examples and explanations to help users understand and apply NumPy's functionalities effectively in their projects.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
