### ISSUE TITLE
Mini Project: Number to Words Converter

### ISSUE THREAD

**Issue by Anshika14528** [animator/learn-python#306]
A Number to Words Converter converts an integer to its equivalent words. 

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
