### ISSUE TITLE
Adding concepts of tuples, dictionaries

### ISSUE THREAD

**Issue by tupur-29** [animator/learn-python#31]
I would like to add concepts of tuples, dictionaries, lists along with connection with database(MySql) concepts. Please add me as a contributor to the project under gssoc'24 and assign this task to me.

**Comment by Pranshu-jais** [comment]
I can add concepts of tuples, dictionaries  with  examples   and program which  help the  readers to understand the concept easily.  I would like this issue to be assigned to me as part of GSSoC'24 with the gssoc label and the appropriate level (1/2/3).
Thank you.

**Comment by animator** [comment]
@tupur-29 @Pranshu-jais Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
