### ISSUE TITLE
Adding mini project: Dice rolling stimulator using Python

### ISSUE THREAD

**Issue by achlbatra** [animator/learn-python#316]
**Python Dice Rolling Simulator**

Description:

The Python Dice Rolling Simulator is a simple yet engaging program designed to mimic the experience of rolling dice. It offers users the ability to simulate rolling one or more dice with customizable options.

Features:

1. **Dice Selection**: Users can select the type of dice they want to roll, including common types like a 4-sided, 6-sided, 8-sided, 10-sided, 12-sided, and 20-sided dice. Additionally, the program could offer custom dice with any number of sides.

2. **Number of Dice**: The simulator allows users to choose how many dice they want to roll at once. They can roll a single die or multiple dice simultaneously, providing flexibility and variation in gameplay.

3. **Rolling Mechanism**: The program simulates the rolling action of physical dice, generating random numbers based on the selected dice type and quantity. It utilizes Python's random module to ensure unbiased and unpredictable results.

4. **Visual Representation**: The simulator can display the results of each roll in a visually appealing format, such as text-based output showing the numbers rolled on each die. Additionally, it could include graphical elements like animated dice rolling to enhance the user experience.

5. **Sum of Rolls**: For scenarios where the total sum of multiple dice rolls is important (e.g., in tabletop role-playing games), the simulator calculates and displays the combined result of all rolled dice.

6. **User Interaction**: The program provides a user-friendly interface, allowing users to input their preferences through command-line prompts or a graphical user interface (GUI). It can also handle user errors gracefully, providing helpful messages in case of invalid inputs.

7. **Customization Options**: Users have the flexibility to customize various aspects of the dice rolling experience, such as adjusting the appearance of the dice, setting default options for future rolls, or incorporating sound effects for added immersion.

Overall, the Python Dice Rolling Simulator offers a fun and interactive way to experience the thrill of rolling dice virtually. Whether used for gaming, educational purposes, or sheer entertainment, it provides a versatile tool for simulating random outcomes in a controlled environment.

**Comment by achlbatra** [comment]
can you describe the content project i need to add to the website? 
Introduction, Code and outputs are my ideas. i would like to know your suggestions

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
