### ISSUE TITLE
Conditional statements

### ISSUE THREAD

**Issue by keerthi-ganiger** [animator/learn-python#32]
In the introductory part of conditional statements elif keyword is not included at all . But at later part in flowcharts and examples its included. So I request you to grant the permission to include details about elif keyword in introductory part also.

<img width="521" alt="i2" src="https://github.com/animator/learn-python/assets/169129430/a428bafd-ff4c-4cf4-9bf8-743eaa859169">

**Comment by rashmitha155** [comment]
Hello @animator, I noticed that in your discussion about jump statements, you've covered `break`, `pass`, and `continue`. However, the `return` statement, which is also a part of jump statements, was not mentioned. 

I would like to request your permission to include details about the `return` statement, along with examples. I'm interested in contributing this information as part of GSSOC24. 

Could you please assign the appropriate labels to this task? Thank you.

**Comment by rashmitha155** [comment]
Hello @animator, I noticed that in your discussion about control flow statements, you've covered `if-else`, `for`, and `while`. However, the `elif` and `switch` statements, which are also a part of control flow statements, were not mentioned. 

I would like to request your permission to include details about the `elif` and `switch` statements, along with examples. I'm interested in contributing this information. 

Could you please assign the appropriate labels to this task? Thank you.

**Comment by animator** [comment]
@rashmitha155 @keerthi-ganiger Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
