### ISSUE TITLE
Implementing Linear Regression Algorithm with Python

### ISSUE THREAD

**Issue by Rithish5513U** [animator/learn-python#320]
Name : Rithish S
email : [rithish.satish@gmail.com](mailto:rithish.satish@gmail.com)
GSSoc'24 Contributor
Github id : @Rithish5513U

I am gonna explain about the Linear regression algorithm in machine learning so that people can easily understand it.
I'm gonna implement it with jupyter notebook for the interactive coding experience.

Also I will make sure to keep it as simple as possible

Assign the task to me

**Comment by Debargha-Saha** [comment]
Hi,I'm Debargha Saha
Mail:debargha.saha.ds25@heritageit.edu.in
I would like to contribute to Linear Regression using python.I would explain all the terms and functions I would used for implementing it.I would also add data visulisations so it becomes interactive for the one reading it.I have also previously implemeneted it in jupyter notebook on a data consisting of 1000 randomly generated x & y values and so  have the required knowledge for solving this task. I also have the code ready withn my system.

So I would request you to assign the task to me

**Comment by Tushar-Vij** [comment]
I would like to work on this issue, please assign this to me sir @animator

**Comment by Rithish5513U** [comment]
But why
