### ISSUE TITLE
Supervised and Unsupervised ML algorithms

### ISSUE THREAD

**Issue by Rithish5513U** [animator/learn-python#322]
I want to provide knowledge about supervised and unsupervised algorithms in ML.
It will be useful for the beginners to understand what is supervised and unsupervised algorithm so that their learning will be efficient.
I love to get assigned to this task so that I provide knowledge to the people

**Comment by tejaswi-c** [comment]
Hello,Iam tejaswi.
I am GSSoC'24 contributor. I would like to work on the issue.
I've good knowledge on data visualization
Kindly assign me the issue.
