### ISSUE TITLE
Binomial Distribution using Python

### ISSUE THREAD

**Issue by Rithish5513U** [animator/learn-python#324]
I like to explain the implementation of Binomial Distribution which is a discrete probability distribution.
I will implement it in jupyter notebook.
It is a basic Distribution to find possible outcomes for a given no of trails.

I like to explain it deeper. I will be happy if I'm assigned.

**Comment by Debargha-Saha** [comment]
Hi,I'm Debargha Saha
Mail:debargha.saha.ds25@heritageit.edu.in
I would like to contribute to the Binomial distribution using python.I would explain all the terms and functions I would used for implementing it.I would also add data visulisations so it becomes interactive for the one reading it.I have also previously implemeneted it in jupyter notebook and have the required knowledge for solving this task and also have a strong background in Probability & Statistics 

So I would request you to assign the task to me
