### ISSUE TITLE
Data Visulization using Seaborn

### ISSUE THREAD

**Issue by Debargha-Saha** [animator/learn-python#326]
Hi,I'm Debargha Saha
Mail:debargha.saha.ds25@heritageit.edu.in
I would like to add data visulation tasks using Seaborn library in Python.I would show scatter plot,bar plot,histogram&kde,box plot and many more

**Comment by tejaswi-c** [comment]
Hello,Iam tejaswi.
I am GSSoC'24 contributor. I would like to work on the issue.
I've good knowledge on data visualization 
Kindly assign me the issue.
