### ISSUE TITLE
Regarding Some Enhancements

### ISSUE THREAD

**Issue by milansamuel609** [animator/learn-python#33]
1) A main page can be added for a good looking UI from where we can go to different sections.
2) A coding compiler can be added like from other website like when we click on the link it will take us to the page where we code live with the progress in study also.
3) We can add some dynamic feature like showing how arrays and other things works.

   If you think this all things are good for enhancements kindly plz reply yes so that I can start implementing.

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
