### ISSUE TITLE
Mini Project:Word Grid Game 

### ISSUE THREAD

**Issue by ImmidiSivani** [animator/learn-python#338]
I want to create a python game where  user needs to choose  two grids[each grid consists of 2 letters] to form words if words are meaningful score will be increased.
Please assign this to me under GSSOC'24

**Comment by 21atha** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24, it would be helpful if you add label for this issue

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
