### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by keerthi-ganiger** [animator/learn-python#34]
I would like to work on adding more exercises on loops for enhanced concept clarity by including questions on fibonacci series and printing different patterns using loops.

**Comment by Niharkoche** [comment]
Can I contribute I understand what you want to add in it

**Comment by rashmitha155** [comment]
I’d be happy to provide more information on nested loops in Python with suitable examples. And also, I would like to include additional information on nested loops which can be used in complex data structures.

can I contribute this issue under GSSOC24.
I would like to request to provide me labels such as gssoc level1, level2, level3

**Comment by Pranshu-jais** [comment]
Loop in  python is one of my favorite topic and i can provide information on loop as well as nested loops  with   examples and simple programs  which  will make  this concept easier to understand  . I would like this issue to be assigned to me as part of GSSoC'24 with the gssoc label and the appropriate level (1/2/3).
Thank you

**Comment by mubinasyed28** [comment]
I would like to help you with adding loops! Can you please assign the issue to me under GSSoC'24?

**Comment by animator** [comment]
@keerthi-ganiger @Niharkoche @rashmitha155 @Pranshu-jais @mubinasyed28 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
