### ISSUE TITLE
Dark Mode Feature for Home Page.

### ISSUE THREAD

**Issue by KrishnaSaxena108** [animator/learn-python#342]
Hello there, @animator!
i would like to contribute to this innovative python learning website by introducing a dark mode feature to enhance it's versatility.
Please assign this task to me under GSSoC'24.
Regards.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
