### ISSUE TITLE
[Add Content] Introduction To Stacks

### ISSUE THREAD

**Issue by somyasaxena01** [animator/learn-python#349]

**Comment by somyasaxena01** [comment]
Hello @animator , I am  a GSSoC'24 Contributor. I would like to contribute to your project by adding content on Introduction To Stacks. Please assign this issue to me.
Topics Covered :-
1. Introduction
2. What are Stacks ?
3. Operations in Stacks
4. Real life examples

**Comment by lakshay-111** [comment]
hey @animator , I would also like to work on this project and will add content on Stacks. I also contributed to your OOPs topic .SO, please assign me this issue now so that i can start working on it . Thanks.
