### ISSUE TITLE
Enhancing Python Learning Experience with Advanced Features

### ISSUE THREAD

**Issue by lakshay-111** [animator/learn-python#35]
I'm working on python from past 3 year and have great experience in it . And I would like to fix the minor bugs and errors in the code and much more theory regarding a topic and summary of their working with their code for better understanding. 
I would also like to add some advances topics in this like :
-Sorting algorithms
-OOPs concept ( Inheritance , Objects , Polymorphism , Memoization , Abstraction , Access modifiers , Encapsulation , Dunder Methods)
-JSON
-OS module
-File Handling
-RegEx (Regular Expressions)
-Generators , Decorators , Clousure , Functools, lambdas ,Wrappers
-Python SQLite
-MYSQL
-Dynamic Programming
-Recursion

I would also add some advanced topics related to the current topics that are currently in your projects like nested list ,tuples , dictionary etc. with their code for better understanding.
 
So, I request you to please assign me this issue so that I can work on it and contribute in it for GSSOC' 24.
@animator

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
