### ISSUE TITLE
Hangman Game using Python

### ISSUE THREAD

**Issue by Yogeshkarma** [animator/learn-python#359]
Description for the game
The hangman game is a multiplayer game. In this game, one player selects a word. Other players have a certain number of guesses to guess the characters in the word. If the players are able to guess the characters in the entire word within certain attempts, they win. Otherwise, they lose.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
