### ISSUE TITLE
Concept of Nested Tuples

### ISSUE THREAD

**Issue by Maryam-Sikander** [animator/learn-python#36]
I feel it would be beneficial to provide further clarification on the concept of nested tuples, including additional examples, and how we can access nested tuples using loops.

**Comment by Pranshu-jais** [comment]
I can add concepts of nested  tuples with examples and program which help the readers to understand the concept easily. I would like this issue to be assigned to me as part of GSSoC'24 with the gssoc label and the appropriate level (1/2/3).
Thank you

**Comment by SaiSruthisri** [comment]
Hello @animator 
I have recently learned python & have good knowledge in it & even used it one of my project (can view it in my account) .
So I believe I can explain this topic in the most simplest way possible to make understand the concept as well as the its application.I will use interesting examples & programs to get more grip on nested tuples.
So please assign this to be under GSSOC'24 & kindly label it with appropriate level.
Thank you in advance!.

**Comment by animator** [comment]
@Maryam-Sikander @SaiSruthisri @Pranshu-jais Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
