### ISSUE TITLE
Time Series Analysis in Python

### ISSUE THREAD

**Issue by Eshparsi** [animator/learn-python#375]
Could you assign this task to me under gssoc 24. I would like to take on this task to Analyze Time Series Data in Python and focus on the following aspects like:
1 Reading and Displaying Data
2. Stationarity
3. Autocorrelation
4. Decomposition
5. Forecasting 
and more

**Comment by Eshparsi** [comment]
Could you assign this task to me under gssoc 24. I would like to take on this task to Analyze Time Series Data in Python and focus on the following aspects like:
1 Reading and Displaying Data
2. Stationarity
3. Autocorrelation
4. Decomposition
5. Forecasting 
and more

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
