### ISSUE TITLE
OOPs is not discussed

### ISSUE THREAD

**Issue by nagamukesh** [animator/learn-python#38]
I would like to add some sections to explain OOPs as object-oriented programming is a very crucial part in Python and I will try to add some exercises for OOPs
please assign this issue under gssoc 2024

**Comment by rashmitha155** [comment]
Thank you for this comprehensive guide on Python 3. It's clear and well-structured, making it easy for beginners to follow. 
I noticed that the guide currently doesn't cover Object-Oriented Programming (OOP) concepts, which are fundamental in Python and many other languages. I believe adding a section on OOP would greatly enhance the guide. This section could cover topics such as classes, objects, inheritance, polymorphism, encapsulation, and abstraction, complete with examples and exercises.

I'd be happy to contribute this content if you think it would be beneficial. Looking forward to your feedback.
Please include levels under gsscoc..

**Comment by SaiSruthisri** [comment]
Hello @animator
I see that the guide is all well structured.And to my notice oops concept is missing.As it is known oops is an important concept & I would be glad to have the chance  contribute to this.
I have recently learned python & have good knowledge in it & even used it one of my project (can view it in my account) .
So I believe I can explain this topic in the most simplest way possible to make understand the concept as well as the its application.I will use interesting examples & programs to get more grip on .
So please assign this to be under GSSOC'24 & kindly label it with appropriate level.
Thank you in advance!.

**Comment by animator** [comment]
@nagamukesh @rashmitha155 @SaiSruthisri Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
