### ISSUE TITLE
GSSOC'24: Adding content on Graph Algorithms to Data Structure And Algorithms

### ISSUE THREAD

**Issue by yashasvi232** [animator/learn-python#385]
hi @animator, I would like to contribute to this project by adding content on graph algorithms. I intend to cover topics:
1.)  BFS and DFS
2.) Djisktra's Algorithm(shortest path in a graph)
3.) Topological sort
4.) Minimum Spanning Tree
Please assign this issue to me and add the appropriate labels.

**Comment by vinay-sagar123** [comment]
Kindly assign this issue to me also.

**Comment by abhi-la-sha** [comment]
@animator Kindly add labels to this issue and assign it to me.

I'd like to add topics like:
1. Components of a Graph
2. Basic Operations on Graphs
3. Applications of Graph
4. BFS and DFS in Graph
5. Shortest Path in Graph (Dijkstra's algo and Warshall's algo)
6. Minimum Spanning Tree (Prim's and Krushkal's)
7. Connectivity in Graph
8. Maximum flow in graph
9. Some problems
@animator 

![image](https://github.com/animator/learn-python/assets/154429742/5a0b5fbc-9f45-4971-830c-fba3e190f14e)
![WhatsApp Image 2024-05-18 at 17 12 58_6ef6feca](https://github.com/animator/learn-python/assets/154429742/9246001e-7a43-426a-a6d6-0e2de69ad67a)
