### ISSUE TITLE
Feat: Automate greeting using Github bot 🤖

### ISSUE THREAD

**Issue by shubhammjha22** [animator/learn-python#386]
Is your feature request related to a problem? Please describe.
As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

Describe the solution you'd like
I would like to add a github bot , which would greet the user whenever there is a PR request or a issue raised
with something like

For PR
"Awesome work, @username! 🎉 Thank you for submitting pull request.
We truly appreciate your contribution and efforts to enhance our project.
Please ensure that you have followed the contributing guidelines for a smooth review process"

For Issue
"Hello @userName,
Thanks for creating this issue and contributing to Tourism!
@admin will review your issue soon and provide feedback. In the meantime, feel free to join the discord community. Please ensure that you have followed the contributing guidelines for a smooth review process"

@animator Please Assign this issue to me under Gssoc'24

**Comment by shubhammjha22** [comment]
@animator  i would like to work on this , can you please assign me this issue .

**Comment by animator** [comment]
Read the contributing guide properly to learn what kind of contributions this project is open to.
