### ISSUE TITLE
Improve CLarity and quality of the content!

### ISSUE THREAD

**Issue by rashmitha155** [animator/learn-python#39]
I’ve been going through the comprehensive guide on Python 3 and found it to be very informative and well-structured. 
 Additionally, I’ve noticed a few areas in the existing content where the language could be clarified or improved. For instance, the phrase “Please search issues and pull requests before adding something new to avoid duplicating efforts and conversations” could be rephrased for clarity as “Before adding something new, please search through existing issues and pull requests to avoid duplicating efforts and discussions”.
 I’d be happy to contribute this content if you think it would be beneficial. Looking forward to your feedback.

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
