### ISSUE TITLE
[Feature]: Adding bookmark,highlight [User login/signup]

### ISSUE THREAD

**Issue by adarsh1001111** [animator/learn-python#40]
Since, this is a **book** made for learning python, the book should have a bookmark feature to remember till where you completed the book and highlight the text user seems important.
Adding a **Login/Signup page** enables a user to personalise this book the way he likes by giving additional features like **bookmark,highlighting.**
Ofc they can access the book without login but the data won't be saved.

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
