### ISSUE TITLE
Advanced Python topics

### ISSUE THREAD

**Issue by tejaswi-c** [animator/learn-python#403]
I would like to provide detailed information on  OOP In Python, Generators, List Comprehensions, Lambda functions, Regular Expressions, Exception Handling, Closures, Decorators, Map, Filter, Reduce functions. If possible kindly assign me this issue.@animator Thank you for guiding.Could you plz assign me this issue under GSSoC'24 if possible

**Comment by animator** [comment]
Choose one topic not a whole bunch of things.

**Comment by tejaswi-c** [comment]
I would like to provide detailed information on List Comprehensions. If possible kindly assign me this issue.@animator Thank you for guiding.Could you plz assign me this issue under GSSoC'24 if possible
