### ISSUE TITLE
[Add Content] NumPy: Concatenation of Array

### ISSUE THREAD

**Issue by manmita** [animator/learn-python#404]
Hello @animator I would like to contribute by adding content about concatenation of arrays in NumPy. 

Topic includes various functions to concatenate arrays in different ways like: 
- Concatenation along different axes
- Concatenation with mixed dimensions
and etc.

**Comment by DeepikaMunimadagu** [comment]
Hello @animator I would like to add to the content about array concatenation in numpy 
Topics covered -
1. intro to function
2. Syntax with explanation
3. Examples and result

For GSSOC'24
