### ISSUE TITLE
Addition of Queue

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#408]
I would like to add a brief introduction to linear queue, basic operations along with illustrations. Please assign this to me.

**Comment by Akshitha28112004** [comment]
Hey, I am good at python. Can you please assign me this issue under gssoc'24?

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
