### ISSUE TITLE
Building a Linear Regression Model with Mathematical Implementation 

### ISSUE THREAD

**Issue by Vaibhavlanjewar** [animator/learn-python#410]
Here, I would like to build a Linear Regression Model in supervised Machine learning. Where I Implement the model from scratch with the mathematics i.e. by using the equation of the line.

I believe I should get a chance to showcase my knowledge of Python and mathematics which is applied in Real-world application.
I am eagerly waiting to assign the task 

-your contributor

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by animator** [comment]
Use scikit-learn.

**Comment by Vaibhavlanjewar** [comment]
Sir can you assign me once again,it is by mistackely click led to not assigned.Please Sir
