### ISSUE TITLE
[Add Content] Numpy Array Shape and Reshaping

### ISSUE THREAD

**Issue by Rupa-Rd** [animator/learn-python#411]
I would like to contribute by adding content on numpy array shapes and reshaping topics.

Expected contents:
1. Intro to array dimensions
2. shape(), reshape() and resize() functions
3. Example usage

I'm a GSSOC '24 contributor. Kindly assign this issue to me!

**Comment by 45Aditya** [comment]
I am excited to contribute to your project by adding content on Numpy array shapes and reshaping topics. Below is the expected content outline:

1- Introduction to array dimensions
2- Explanation of shape(), reshape(), resize() , and many other functions
3- Example usage and practical demonstrations


As a GSSOC '24 contributor, I am enthusiastic about contributing meaningfully to your project. Kindly consider assigning this issue to me, and I will ensure timely and quality completion.

Looking forward to contributing to your project.
