### ISSUE TITLE
[Add Content] Numpy datatypes

### ISSUE THREAD

**Issue by Rupa-Rd** [animator/learn-python#412]
I would like to add content on numpy datatypes

Expected contents:
1. Intro to numpy datatypes
2. List of datatypes
3. Example for each datatypes
4. numpy functions with example (`dtype` and `astype`)

@animator, Kindly assign this issue to me under GSSoC '24.

**Comment by AnshitaSingh123** [comment]
I propose to undertake the following tasks:

Elaborate on the different NumPy datatypes, including int, float, complex, bool, and custom dtypes.
Provide practical examples demonstrating how to use each datatype effectively.
Highlight the implications of choosing different datatypes on performance and memory usage.
Offer tips and best practices for datatype selection in various scenarios.
I am confident that my contributions will add significant value to the NumPy documentation, making it a more robust resource for users at all levels.
Please assign this task to me.
