### ISSUE TITLE
Live video capture  manipulation uisng numpy 

### ISSUE THREAD

**Issue by litesh1123** [animator/learn-python#416]
numpy can be also used for pixel manipulation and many other requirements. live video capture manipulation is one of its use case
![live_video_manipu](https://github.com/animator/learn-python/assets/139573484/195493a0-cb72-4e60-a4a5-2b698055e273)
>this will unveil new use cases of numpy

**Comment by animator** [comment]
Please stick to the topics mentioned in the Contributing guide.
