### ISSUE TITLE
Usage of numpy to edit live video stream to gray scale

### ISSUE THREAD

**Issue by litesh1123** [animator/learn-python#417]
using numpy we can edit live video stream to gray scale making it black and white  and get it back to normal 
normal image :
![normal](https://github.com/animator/learn-python/assets/139573484/0a0f2695-e95e-43a7-a91e-0df1d37ba760)
gray image:
![gray](https://github.com/animator/learn-python/assets/139573484/0089e97c-8615-43bd-949d-bb1b82c7d403)

**Comment by animator** [comment]
Please stick to the topics mentioned in the Contributing guide.
