### ISSUE TITLE
Reimagining Reality: Numpy's Spotlight on Negative and HSV Transformations

### ISSUE THREAD

**Issue by litesh1123** [animator/learn-python#418]
live video stream  can be converted  to
>hsv(recording temperatures)
>negative(image reel)
>negative hsv
>rgb
>gray
all this can be captured with normal webcam but with use of numpy
hsv :
![hsv](https://github.com/animator/learn-python/assets/139573484/2919f47c-246b-43cc-b377-f8621ebdacd2)
negative :
![negative](https://github.com/animator/learn-python/assets/139573484/19493564-bf0f-4bd0-b959-f1b1d3307b7d)
negative hsv:
![negative hsv](https://github.com/animator/learn-python/assets/139573484/6b17d89e-7832-4f6c-bbea-5eafb0377378)

**Comment by litesh1123** [comment]
normal :
![normal](https://github.com/animator/learn-python/assets/139573484/1bdfb5fa-8caa-499c-a28c-d3855e88c7e5)

**Comment by animator** [comment]
Please stick to the topics mentioned in the Contributing guide.
