### ISSUE TITLE
Adding Pattern Problems 

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#419]
I would like to add some pattern questions using loops which will help the readers have a better understanding of loops.

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by JanitKumar** [comment]
I can add various pattern please assign it to me
@animator

**Comment by Akshitha28112004** [comment]
Hey, I am excellent in python and have solved many of these questions. Can you please assign me this issue under gssoc'24?

**Comment by Tejasri-Pendota** [comment]
I have some begginer friendly to brain stroming patter problems which will help users to improve their logical thinking. 

I would like to work on this issue. Please assign it to me under the lable gssoc

**Comment by 2305e3ish** [comment]
Hey @animator , I have all information on Pattern problems from beginners all the way to adding emojis and colours and huge figures like umbrellas using pattern concept. I would like to work on this issue.Please assign it to me under gssoc.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
