### ISSUE TITLE
RegEx

### ISSUE THREAD

**Issue by snehatungana** [animator/learn-python#42]
The topic RegEx is not explained in the documentation so far. I would like to propose the addition of RegEx, which is quite important in string handling. I would like to include :
1. What is RegEx
2. How to install and import the re module 
3. RegEx functions 
4. Metacharacters
5. Special Sequences 
6. How to modify strings using RegEx functions 

I would demonstrate the proper usage of all functions with examples showing the logic, input and output.

**Comment by snehatungana** [comment]
I would like to work on this issue for GSSoC 2024. Kindly assign this issue to me. @animator

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
