### ISSUE TITLE
Finding out geospatial data  with help of python

### ISSUE THREAD

**Issue by litesh1123** [animator/learn-python#422]
Creating user interface were user can find latitude ,longitude, and other geospatial data features of any place in world  .
>use case: geospatial data can be tracked down with help of python
>can be used in projects where maps are widely used ,where location ,coordinates are needed.

Geospatial data of Any place on planet earth can be found out with help of python

**Comment by animator** [comment]
Please stick to the topics mentioned in the Contributing guide.
