### ISSUE TITLE
Optimizing searching wth the help of python

### ISSUE THREAD

**Issue by litesh1123** [animator/learn-python#423]
Creating user interface
>Integration of Search engine like google and brave with python 
>integration of youtube with python
generally searching process in youtube or google takes five steps where
Opens browser > user opens YouTube/google search bar > enters details of what he wants to search  > waits for searching > gets output

it can be reduced to four steps
user opens youtube/google from pinning to task bar > enters details of what he wants to search  > waits for searching > gets output

But i have reduced it to two steps
user enters what he want to be searched > gets output 

step1:
![search1](https://github.com/animator/learn-python/assets/139573484/8ec28bf8-78c2-4126-9dbb-845c587524fd)

step 2:
![output](https://github.com/animator/learn-python/assets/139573484/80f21164-6795-42b0-9c87-0cf1921734e4)

**Comment by animator** [comment]
Please stick to the topics mentioned in the Contributing guide.
