### ISSUE TITLE
Controlling Cloud services with help of python (boto3 module)

### ISSUE THREAD

**Issue by litesh1123** [animator/learn-python#424]
We can use Python to control many cloud services
> Use case : in many projects where we want to implement cloud services we use Python to integrate the cloud with the project
> In this part i will be using
>creating ec2 instance
> List down total number of ec2 instances in cloud
>removing ec2 instances
>creating s3 bucket 
This is classic case of a cross-over of two technologies

**Comment by animator** [comment]
Please stick to the topics mentioned in the Contributing guide.

**Comment by litesh1123** [comment]
Hello @animator shall i deliver application and advantage of boto3 module in in documented format

**Comment by litesh1123** [comment]
@animator other issues raised by me  with different types of modules do i have to provide documentation
