### ISSUE TITLE
Python Mini-Games With  Use of Random Library 

### ISSUE THREAD

**Issue by Dhruv100404** [animator/learn-python#440]
Use of Maths and Random Library

**Comment by Dhruv100404** [comment]
Assign these to me I have build 2-3 games already and I have 2-3 more ideas

**Comment by AnshitaSingh123** [comment]
As a passionate Python developer with a keen interest in game development, I am excited about the opportunity to bring my skills and creativity to this.
With a solid background in Python programming, I have extensively utilized the random library in various projects, which has honed my ability to implement randomized logic and enhance the unpredictability and engagement of games.
Please assign this task to me and add labels.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
