### ISSUE TITLE
Adding List Comprehension

### ISSUE THREAD

**Issue by tejaswi-c** [animator/learn-python#441]
I would like to provide detailed information on List Comprehensions and advanced list comprehension techniques. @animator If possible kindly assign me this issue under GSSoC'24.

**Comment by MadamPujitha** [comment]
I can fix this issue by adding the detailed information on list comprehension .If possible assign this issue to me.

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
