### ISSUE TITLE
adding searching algorithm under dsa

### ISSUE THREAD

**Issue by AtulYadavCodes** [animator/learn-python#443]
i would like to add linear search and binary search algorithm

**Comment by AtulYadavCodes** [comment]
@animator

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
