### ISSUE TITLE
[Feature]: I think we should also add some Data Science and Machine Learning libraries content.

### ISSUE THREAD

**Issue by kRiShNa-429407** [animator/learn-python#45]
I can make content for it in a simple and easy way.
Learners can easily understand it

**Comment by animator** [comment]
@kRiShNa-429407 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.

**Comment by kRiShNa-429407** [comment]
Okk
Thank you for your response
