### ISSUE TITLE
Adding Time series visualization

### ISSUE THREAD

**Issue by tejaswi-c** [animator/learn-python#451]
I would like to provide detailed information on time series analysis using different data visualization techniques
-Techniques for data visualization for time-series analysis
   1.Line Plots
   2.Area Plots
   3.Seasonal decomposition plots
   4.Moving Averages
   5.Seasonal subseries plots
   6.Auto correlation plots
   7.Time series decomposition using STL 
   8.Anomaly detection
   9.Heatmaps

@animator kindly assign me this issue. This will be helpful if documented properly

**Comment by animator** [comment]
Choose a single small section for which you will be contributing and raise a new issue.
