### ISSUE TITLE
Adding Python Snake game

### ISSUE THREAD

**Issue by DeepikaMunimadagu** [animator/learn-python#452]
Hello I want to add a snake game using python. Please assign this task to me.
GSSOC'24

**Comment by DeepikaMunimadagu** [comment]
The game will be the same as the mobile game the snake will get bigger by eating to more and more food and a game over message will be displayed if the snake's mouth touches the walls.

**Comment by AnshitaSingh123** [comment]
I want to add this snake game. Please consider my request of assigning this task to me.

**Comment by 45Aditya** [comment]
Hii, I want to contribute to this. Kindly believe in my skills and assign it to me.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
