### ISSUE TITLE
Adding Information about PiP in Packages ssection

### ISSUE THREAD

**Issue by seeratfatima19** [animator/learn-python#455]
Pip is python package manager which is essentially used to manage, install and uninstall almost all python packages. I want to add some hands-on information about Pip so that students will be able to complete their everyday tasks with use of Pip.

Kindly assign this issue to me under the label GSSoC'24

Thanks and regards

**Comment by Tejasri-Pendota** [comment]
I'd like to add information about PiP (Python Package Index) to the Packages section, including installation instructions, managing dependencies, and common commands. Once assigned, I will thoroughly research, draft the content, and submit a pull request for review. This task aligns with my skills and will help me gain valuable experience.

Kindly assign this issue to me under the label GSSoC'24

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
