### ISSUE TITLE
Adding dark mode to the page.

### ISSUE THREAD

**Issue by sshivangi882** [animator/learn-python#460]
As a programmer we generally prefer dark mode , let me add a dark mode button through which we can switch the modes accordingly.

**Comment by 2305e3ish** [comment]
#animator I would like to add this feautre.Please assign this to me under GSSoC'24.

**Comment by 45Aditya** [comment]
I would love to enhance user experience by adding a dark mode toggle button for your project, making it more accessible and appealing to users.
