### ISSUE TITLE
[Add Content] Introduction to GUI using Python and Tkinter

### ISSUE THREAD

**Issue by Arya-Hari** [animator/learn-python#468]
I would like to add content on "Introduction to Graphical User Interface Design using Python and Tkinter".

Expected contents : 

1. Overview and Introduction
2. Understanding Tkinter
3. Installing Tkinter
4. Hello World and Simple Tkinter app

@animator Kindly assign this issue to me for GSSoC '24. Thank you!

**Comment by 2305e3ish** [comment]
@animator i have done various projects using GUI-Tkinter module in Python.
i am confident i can add information on this topic. Please assign this to me under GSSoC'24.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
