### ISSUE TITLE
[Add content] Adding features and brief description of MatPlotLib Library

### ISSUE THREAD

**Issue by Harshita297** [animator/learn-python#469]
I would like to introduce the Matplotlib library, describing:
1.] Its resemblance with MATLAB
2.] Various plots and graphs with examples

@animator kindly assign this task to me for GSSOC'24
Thank You.

**Comment by anamika23428** [comment]
I would like to introduce the Matplotlib library and show how to create different types of plots with it.
@animator, please assign this task to me for GSSOC'24.
Thank you!
