### ISSUE TITLE
Add some edge-cutting technologies like AIML , Data Science and Cybersecurity (PythonScripts) with Python and some real life oriented projects

### ISSUE THREAD

**Issue by Yashpreeth** [animator/learn-python#47]
Heyy @animator ,
I have gone through your repository. Since you have covered a lot of the Python course material, I would like to suggest one additional thing in addition to how much I would appreciate having such inventive repositories: why can not we add some cutting-edge technologies like AIML, Data Science, and Cybersecurity (PythonScripts)? They will be much more beneficial to the repository.
I hope you will assign the issue to me.
thank you

**Comment by animator** [comment]
@Yashpreeth Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
