### ISSUE TITLE
[Add content] Adding "Python in Machine Learning"

### ISSUE THREAD

**Issue by Harshita297** [animator/learn-python#470]
Implementation of all machine learning algorithms via Python:
1.] Linear and Logistic regression
2.] K-means clustering
3.] K-NN
4.] Naive Bayers
5.] Decision Tree
6.] Random Forest Classifier
@animator Kindly assign this task to me under GSSOC'24
Thank You.

**Comment by animator** [comment]
Choose a single small section for which you will be contributing and raise a new issue.
