### ISSUE TITLE
Adding Seaborn library content

### ISSUE THREAD

**Issue by ChethanaPotukanam** [animator/learn-python#476]
I want to add content about Seaborn library like:
  -How to install it
  -Comparison with Matplotlib
  -Different  Seaborn plots
  -Why is it necessary to use Seaborn in data visualisation

Please assign this task to me under gssoc'24.
Thank You.

**Comment by animator** [comment]
You cannot choose an entire topic or a whole bunch of sections.
Choose a single section for which you will be contributing and raise a new issue.

**Comment by ChethanaPotukanam** [comment]
Ok @animator
