### ISSUE TITLE
Add Content: Cursor and turtle package

### ISSUE THREAD

**Issue by Vikranth3140** [animator/learn-python#478]
I would like to add content to the Cursor and turtle package.

[Cursor](https://pypi.org/project/cursor/)

[turtle](https://docs.python.org/3/library/turtle.html)

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
