### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by AtharvKasar04** [animator/learn-python#48]
- There is no favicon displayed on the website.
- I will add a relevant favicon to compliment the website.

@animator Can you please assign this issue to me under GSSoC'24. 
It would be great to work on this issue.

**Comment by vignesh-0512** [comment]
As a gssoc'24 contributor, i would like to work on this issue so can you please assign me this issue.

**Comment by animator** [comment]
@vignesh-0512 @AtharvKasar04 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.

**Comment by vignesh-0512** [comment]
Thanks for your reply @animator will work on this and soon we will be raising a PR can you please share any image to add as a favicon

**Comment by animator** [comment]
@vignesh-0512 Read the Contribution Guide properly. No website changes are allowed.

**Comment by vignesh-0512** [comment]
Thanks for your reply @animator
