### ISSUE TITLE
[ADD CONTENT]: Introduction to Python MySQL in the Interacting with Databases segment

### ISSUE THREAD

**Issue by arihunter-18** [animator/learn-python#490]
Hi @animator, I am a GSSOC'24 contributor and willing to add content in the Interacting with Databases segment. The introduction includes setting up the environment for MySQL Connector and executing the basic SQL Queries.
Kindly assign this issue to me.
Thank You

**Comment by shiwanijain** [comment]
Hello.
I m willing to add content about Database interaction using MySQL and the elaborative usage of SQL queries and its implementation.
I am a GSSOC'24 contributor.
I request you to please kindly this issue to me
Thank you
