### ISSUE TITLE
Revisit my pull request from that project 

### ISSUE THREAD

**Issue by Kavin56** [animator/learn-python#491]
Do you even have an iota of shame. Copying [someone else](https://github.com/shrawani21)'s work and claiming it as your own. You are barred from contributing to this project.

_Originally posted by @animator in https://github.com/animator/learn-python/issues/272#issuecomment-2117948059_
            
            I want you to revisit my pull request from that project mentor anf know the truth behind it.
            
I have contributed to that project and please don't disrespect without knowing the truth

this is the pull request to that project which is done by me:

https://github.com/shrawani21/gamer_21/pull/43

![image](https://github.com/animator/learn-python/assets/148603725/71913c64-2bd4-4f6f-b6c0-f45f6753bdec)

please dont disrespect others without knowing the truth , and it really hurts

please remove the label ethics-violation

**Comment by animator** [comment]
You might have authored the PR in the main project. But, you violated copyright by not seeking permission of the original project maintainer and adding the entire project as a PR. Also, you never mentioned the original work in the PR which shows ill intent.

**Comment by Kavin56** [comment]
why did you mention ethics violation in this issue ?? give me a reason
and another thing

I have contributed i have the right to submit the project as it's my project

**Comment by Kavin56** [comment]
@animator why are you tagging ethics-violation for this issue, i just asked and i didnt do any violation in this issue.
@manmita @drishangupta @Vrisha213
