### ISSUE TITLE
Is this repository not the part of GSSOC '24?
Because sir your name is in the final list of GSSOC.

### ISSUE THREAD

**Issue by kRiShNa-429407** [animator/learn-python#493]

**Comment by kRiShNa-429407** [comment]
https://docs.google.com/spreadsheets/d/1hvDa1vAmjphSEhtxFvVQEk1snMT4I-0iAWJ_sDTKhg8/edit?usp=sharing

@animator your name is not present in the above list ☝️☝️

**Comment by animator** [comment]
This is the list of mentors. I am the project admin.

**Comment by kRiShNa-429407** [comment]
Okk sir
Thank you for informing
