### ISSUE TITLE
Comparison between ML models

### ISSUE THREAD

**Issue by DivyaVijay1234** [animator/learn-python#496]
I would like to propose a framework that enables a user to choose the appropriate ML model for a particular prediction or classification problem. The aim is to provide clear distinctions between models through flow charts and a code that helps compare the accuracy of different models. The code will also help with hyperparameter tuning. 

I have worked on various ML models before and have a sound understanding of their functionalities and applications. Please assign this issue to me. I look forward to working with you and contributing towards your organization.

**Comment by animator** [comment]
It is not under the current scope of the project.
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add, follow proper process and raise an issue.
