### ISSUE TITLE
Adding NEXT and PREVIOUS buttons to navigate

### ISSUE THREAD

**Issue by AtharvKasar04** [animator/learn-python#50]
- Addition of `Next` and `Previous` buttons for navigations between the sections.
- This would increase convenience to navigate the sections after the user has done with anyone.

@animator Can you please assign me this issue under GSSoC'24, I would love to work on this addition.

**Comment by mubinasyed28** [comment]
I'd like to add the Next and Previous buttons for navigation. 
Can you please assist me in this and assign it the issue to me under GSSoc'24?

**Comment by sasidhara-kashyap0903** [comment]
I'd like to add the Next and Previous buttons for navigation.
Can you please assist me in this and assign it the issue to me under GSSoc'24?

**Comment by animator** [comment]
@AtharvKasar04 @mubinasyed28 @sasidhara-kashyap0903 Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
