### ISSUE TITLE
Adding light and dark mode theme option

### ISSUE THREAD

**Issue by AyushShukla3466** [animator/learn-python#51]
Only dark theme is present but no light theme. 
![python](https://github.com/animator/learn-python/assets/100012862/628eeed5-f23f-4398-901d-49ef0b689b7b)
Light mode is important because it provides a traditional, well-lit interface that enhances readability, reduces eye strain in well-lit environments, and maintains visual consistency with many other digital platforms.

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
