### ISSUE TITLE
[Add Content] Dictionary Data Structure

### ISSUE THREAD

**Issue by shahpranshu27** [animator/learn-python#511]
A dictionary in Python is a data structure that stores key-value pairs, allowing efficient retrieval, insertion, and deletion of elements. It's important in Python because it provides a flexible and efficient way to organize and manipulate data. Dictionaries are commonly used for tasks such as data retrieval, counting, configuration settings, and memorization, making them a crucial component of Python programming for various applications.

**Comment by anoushkaghosh231** [comment]
Hi @shahpranshu27! I am a contributor at GSSOC'2024 and would like to contribute to this project by adding content on Dictionaries in Python. I have worked on this topic previously and would request you to assign this issue to me. Thankyou.
