### ISSUE TITLE
[Add Content] Linked List Data Structure

### ISSUE THREAD

**Issue by shahpranshu27** [animator/learn-python#516]
A linked list is a linear data structure where each element, called a **node**, contains a value and a reference to the next node in the sequence. Unlike arrays, linked lists do not require contiguous memory allocation, allowing for dynamic size adjustments and efficient insertion and deletion operations. This makes them valuable for scenarios where frequent modifications to the data structure are necessary. Linked lists are commonly used in various applications such as memory management systems, implementing stacks and queues, and representing sparse matrices.

**Comment by aasthagupta1** [comment]
A linked list is a linear data structure where each element is a separate object, called a node. Each node contains two items: the data and a reference (or link) to the next node in the sequence. This structure allows for efficient insertion or removal of elements from any position in the sequence during iteration
Define the Node Class:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
