### ISSUE TITLE
[Add mini-project] 2048 game using Tkinter

### ISSUE THREAD

**Issue by shahpranshu27** [animator/learn-python#517]
The **2048** game is a popular single-player sliding block puzzle game. The objective is to slide numbered tiles on a grid to combine them to create a tile with the number 2048. The game is won when a tile with the number 2048 appears on the board, but players can continue to play to achieve higher scores.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
