### ISSUE TITLE
[Add mini-project] Calculator GUI using Tkinter

### ISSUE THREAD

**Issue by shahpranshu27** [animator/learn-python#518]
This Python project utilizes Tkinter to create a user-friendly graphical interface for a basic calculator. The interface features numeric buttons, operator buttons, and special functions like percentage and clear (AC). Users can input numbers and perform arithmetic operations with ease, with the result displayed in a text entry field. The project showcases GUI programming concepts in Python for creating interactive applications.

**Comment by animator** [comment]
Tkinter is not under the scope of this project. Pick another topic and raise a new issue.
