### ISSUE TITLE
Adding python for machine learning content

### ISSUE THREAD

**Issue by NIKITA320495** [animator/learn-python#52]
adding content from easy to higher level of machine learning which include pandas, numpy,matplotlib,datapreprocessing and different machine learning algorithms...as a data science student i can make add relavent content to your project
so please assign it  under GGSOC'24

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
