### ISSUE TITLE
[Add mini project] Mastermind game

### ISSUE THREAD

**Issue by shahpranshu27** [animator/learn-python#520]
This Python project implements a basic version of the Mastermind game, where the player attempts to guess a randomly generated 5-digit number. It utilizes random number generation, input/output handling, loops, and conditional statements to provide an interactive gaming experience. The player receives feedback on their guesses, aiming to crack the code within the fewest number of tries.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
