### ISSUE TITLE
[Add mini project] Memory game

### ISSUE THREAD

**Issue by shahpranshu27** [animator/learn-python#521]
This is a memory game implemented using **SimpleGUICS2Pygame**, where players match pairs of cards with identical numbers. The game starts with a shuffled deck of cards face down. Players flip two cards per turn, trying to remember their locations. If the flipped cards match, they remain face up; otherwise, they're flipped back. The game ends when all pairs are found. It includes a turn counter and a timer to track performance. Players aim to complete the game in fewer turns and a shorter time for a better score.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
