### ISSUE TITLE
Add Content: Naïve Bayes Classifier in Python for Machine Learning

### ISSUE THREAD

**Issue by DivyanshiSingh00** [animator/learn-python#523]
Naive Bayes classifier is a probabilistic machine learning model used for classification purpose.
I want to add this in the machine learning section and give all the details about this topic.

**Comment by DivyanshiSingh00** [comment]
@animator  Please assign me this issue

**Comment by HarshitaSingh198** [comment]
@animator  Please assign this issue to me .I would like to work on this topic.
