### ISSUE TITLE
mini project: Math_Challenge 

### ISSUE THREAD

**Issue by anamika23428** [animator/learn-python#530]
Hello @animator,

I want to add a very basic level mini-project called "Math_Challenge." In this project, we will ask users a series of randomly generated math questions. We will track the time they take to answer and the number of questions they get correct. Additionally, I would like to introduce the eval function in this project to evaluate the math expressions.

I am eager to work on this project. Please assign me this task.

Thank you.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
