### ISSUE TITLE
[Add Mini-Project]a Cab Booking System: Python Project

### ISSUE THREAD

**Issue by revanth1718** [animator/learn-python#539]
Some of the features of the cab booking system using Python are:

1.All the data of users or customers are set up.
2.Select the cabs according to your choice
3.Reserve the cab for those who book it online.
4.It stores all the information of users
5.The cost of cab booking is there along with the tax generation
6.Then booking the receipt
7.Lastly, log in to the system and then fill in the password for the cab booking system.

I am Participating in GSSOC'24

**Comment by animator** [comment]
Not under the scope of this project. Pick another topic and raise a new issue.
