### ISSUE TITLE
Addition of Python Modules(NumPy, Pandas, Plotly, Matplotlib, Sci-kit Learn, Seaborn)

### ISSUE THREAD

**Issue by krish-san** [animator/learn-python#54]
Including essential modules like NumPy, scikit-learn,Pandas, Plotly, Matplotlib, Seaborn can greatly benefit learners as these tools are widely used and crucial for various applications today(especially in the field of data science). They offer practical solutions and can be explained in a clear and understandable manner to help learners grasp their importance and utility effectively.

**Comment by krish-san** [comment]
Hello, Having gained extensive experience with Python over the years, I would be delighted to offer my contribution to this issue.As i have raised the issue, please assign me this issue under GSSoc'24.

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
