### ISSUE TITLE
[Add Content] 

### ISSUE THREAD

**Issue by Arya-Hari** [animator/learn-python#542]
I would like to add content on Data Science and Machine Learning - Introduction to TensorFlow.

Expected contents :

1. Overview and introduction
2. Basics of Tensors
3. Introduction to TensorFlow Variables
4. Introduction to Keras and the Sequential Model
5. Small project using TensorFlow 2 and Keras

@animator Kindly assign this issue to me for GSSoC '24. Thank you!

**Comment by adarshsingh05** [comment]
Hey there please assign me this issue for gssoc 2024 I would love to solve this issue by adding content on the given topic Also I will be adding necessary external links and examples for better understanding. Thank you.

**Comment by PJ40200** [comment]
If this issue is not assigned to anyone, Can you please assign this issue to me under gssoc'24 . I would like to add examples of code, how to use it and detailed explanation.

**Comment by animator** [comment]
Pick a small topic and open a new issue
