### ISSUE TITLE
[Snake Game using Python]

### ISSUE THREAD

**Issue by rahulnarayaniitk** [animator/learn-python#543]
Hey @animator,
I would like to make a game named Snake, which is a classic arcade game.

Features/Functionalities of the game:

1. How do you make the snake faster or slower?
2. How can you make the snake go around the edges?
3. How would you move the food?
4. Change the snake to respond to arrow keys.

@animator, Kindly assign this new issue to me under GSSoC '24 and assign a suitable level to it.

**Comment by animator** [comment]
Games are no longer under the scope of this project. Pick another topic and raise a new issue.
