### ISSUE TITLE
Introduction to Bar Plots in Matplotlib

### ISSUE THREAD

**Issue by piyush-poddar** [animator/learn-python#545]
I want to contribute a new section in [plotting-visualisation](https://github.com/animator/learn-python/tree/main/contrib/plotting-visualization) directory explaining the generation and manipulation of **Bar Plots using Matplotlib** in Python. I will create a comprehensive guide on how to generate various types of Bar Plots using Matplotlib.

Expected Level: **Level 2**

@animator Please assign this issue to me under GSSoC'24.

**Comment by PJ40200** [comment]
If this issue is not assigned to anyone, Can you please assign this issue to me under gssoc

**Comment by piyush-poddar** [comment]
@animator I have created a [PR](https://github.com/animator/learn-python/pull/595) to close this issue. Kindly review it. Thanks!

**Comment by piyush-poddar** [comment]
@animator I have created a new [PR](https://github.com/animator/learn-python/pull/657) with the required changes to close this issue. Kindly review it. Thanks!
