### ISSUE TITLE
Introduction to Pie Charts in Matplotlib

### ISSUE THREAD

**Issue by piyush-poddar** [animator/learn-python#546]
I want to contribute a new section in [plotting-visualisation](https://github.com/animator/learn-python/tree/main/contrib/plotting-visualization) directory explaining the generation and manipulation of **Pie Charts using Matplotlib** in Python. I will create a comprehensive guide on how to generate various types of Pie Charts using Matplotlib.

Expected Level: **Level 2**

@animator Please assign this issue to me under GSSoC'24.

**Comment by PJ40200** [comment]
If this issue is not assigned to anyone, Can you please assign this issue to me under gssoc
