### ISSUE TITLE
[Add Content] Map function

### ISSUE THREAD

**Issue by shahpranshu27** [animator/learn-python#554]
`map()` is a built-in Python function used to apply a specified function to each item of an iterable (like a list) and return a new iterable with the results. It's concise, efficient, and commonly used for data transformation tasks. Its syntax is `map(function, iterable)`, where `function` is the function to apply, and `iterable` is the collection of items.

**Comment by Charu19awasthi** [comment]
many are unknown by the use of map() function as a fresher learner i can contribute well..please assign it to me

**Comment by shahpranshu27** [comment]
> many are unknown by the use of map() function as a fresher learner i can contribute well..please assign it to me

I had already created a PR, and it has been merged too. You can read and learn more about it here
https://github.com/animator/learn-python/blob/main/contrib/advanced-python/map-function.md
