### ISSUE TITLE
[Add Content] : Introduction to Tkinter (GUI Library) in Python 

### ISSUE THREAD

**Issue by ISaumya1011** [animator/learn-python#555]
I want to contribute a new section with Introduction to the GUI Library of Python, TKinter explaining the procedure to work with and create GUI applications, including all sorts of Widgets that can be used. I will create a comprehensive guide on different features and functions of the library.

Expected Level: Level 2

@animator I request you to please assign this issue to me under GSSoC'24.
Thanking you.

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic and raise a new issue.
