### ISSUE TITLE
Adding Pygame Module 

### ISSUE THREAD

**Issue by krish-san** [animator/learn-python#56]
Including the pygame module would be a valuable addition. It's important to articulate Python's role in game development to highlight its significance in this domain.

**Comment by krish-san** [comment]
Hello, I have been working with pygame for quite some time and have always been eager to engage with it. I would like to take on the responsibility of resolving the issue that I have raised. Please assign me under GSSoc'24

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
