### ISSUE TITLE
[Add Content] Implementing Data Structures Utilizing Lists

### ISSUE THREAD

**Issue by ManasiDhotkar** [animator/learn-python#566]
**_Implement common data structures by utilizing list , such as_** 
- **Stack Implementation :** Create a stack data structure using a Python list. Implement operations such as push, pop, and peek.

- **Queue Implementation :** Develop a queue data structure using a Python list. Implement operations such as enqueue, dequeue, and peek.

- **Linked List Implementation :** Design a linked list data structure using Python lists to represent nodes. Implement operations such as insertion, deletion, traversal, and search.

- **Tree Implementation :** Implement basic tree structures (e.g., binary search tree, binary heap) using lists. Implement operations such as insertion, deletion, traversal, and search.

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic and raise a new issue.
