### ISSUE TITLE
[Add Content] Looping techniques

### ISSUE THREAD

**Issue by ManasiDhotkar** [animator/learn-python#567]
### **Looping techniques** 
 The list of the looping techniques mentioned:
1. Dictionary Iteration
2. Enumerate
3. Zip
4. Reversed
5. Sorted
6. Set for Uniqueness
7. Filtering Data

Please assign this issue to me

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic and raise a new issue.
