### ISSUE TITLE
Python Mini Project on Banking Management using OOPS concepts

### ISSUE THREAD

**Issue by saiumasankar** [animator/learn-python#571]
Description: 
I would like to contribute in the Python Mini project section. My idea is use the OOPS concepts in the python to perform various operations like withdrawal, deposit, and other operations using OOPS. This helps in getting good understanding in OOPs.

**Comment by harshitha-256** [comment]
please assign this task to me

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic and raise a new issue.
