### ISSUE TITLE
Trie Data Structure in Python

### ISSUE THREAD

**Issue by saiumasankar** [animator/learn-python#573]
Trie is one of the advanced and important Data Structure. I would like to contribute about Trie in Data structures section. I will explain it by solving some basic to advanced trie problems.

**Comment by akshitajaiswal2908** [comment]
i request you please assign me this task under Gssoc 24 and label it as am starting my journey in open source

**Comment by animator** [comment]
never heard of "Trie" 
Closing this issue.

**Comment by saiumasankar** [comment]
Trie is one of the advanced data structure used to find the occurrences of words in a list of words with common prefix. It is very useful in solving various problems and can reduce the time complexity compared to brute force.

**Comment by animator** [comment]
My bad @saiumasankar 
Go ahead 👍
