### ISSUE TITLE
Web Scrapping using Python

### ISSUE THREAD

**Issue by saiumasankar** [animator/learn-python#574]
I would like to contribute in web scrapping using Python. I would like to use the "Beautiful Soup" Library.

**Comment by akashlogics** [comment]
I have learned many about beautiful soup libraries in Python and in my projects, I had done many web scraping projects. So can you send me this issue so I can work on it 

 And can you label it as Gsoc 24?

**Comment by saiumasankar** [comment]
Could you please tell me why did you close this issue.
