### ISSUE TITLE
Add Content: Send WhatsApp messages with Python!! (mini project).

### ISSUE THREAD

**Issue by kRiShNa-429407** [animator/learn-python#576]
Please assign the issue to me.

**Comment by akashlogics** [comment]
I used to send many messages in WhatsApp using Python and learned **PyWhatKit** as a wrapper around the WhatsApp web application. So can you please assign me this issue?
 
@adarsh1001111 can you add gssoc24 label to it?

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic and raise a new issue.

**Comment by kRiShNa-429407** [comment]
Okk
