### ISSUE TITLE
[ Adding CONTENT ] In Advanced Data Structures

### ISSUE THREAD

**Issue by DhayanandhS** [animator/learn-python#577]
Hey @animator, I have gone through the table of content in the [project](https://animator.github.io/learn-python/#table-of-contents) and this learning method will be very much useful. 

What I would like to add : There are list, dictionary and tuple. But there is no particular section for SETs. So I am willing to added a dedicated section for SETs.

Topics I will cover: 

1. What is a Set?
2. Creating Sets
3. Accessing Set Items
4. Adding Items to a Set
5. Removing Items from a Set
6. Set Operations (Union, Intersection, Difference)
7. Built-in Set Methods

I can add it with the tuple section or after that, so that it will be easy to locate for learners.

Can you please assign this issue to me?

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.
