### ISSUE TITLE
[Add Content] - Introduction to PyTorch

### ISSUE THREAD

**Issue by Arya-Hari** [animator/learn-python#578]
I would like to add content on Data Science and Machine Learning - Introduction to PyTorch

Expected contents :

1. Overview and introduction - What is PyTorch?
2. Key Features and use cases
3. Getting started with PyTorch- Installing PyTorch
4. Basic Example demonstrating its use

Expected level : Level 2
@animator Kindly assign this issue to me for GSSoC '24. Thank you!

**Comment by Arya-Hari** [comment]
@animator I see some other contributor has already added PyTorch related contents yesterday. It covers most of what I wanted to add. Should I continue with the current issue or modify it to add extra content?

**Comment by animator** [comment]
modify
