### ISSUE TITLE
Addition of content on Data Science and Machine learning.

### ISSUE THREAD

**Issue by Hemav009** [animator/learn-python#58]
@animator 
I want to add content on Data Science & Machine Learning: Scikit-learn, TensorFlow, PyTorch, regression, classification, clustering, ensemble model, deep learning, etc.

please assign me.
Thank YOU!

**Comment by animator** [comment]
You cannot choose an entire topic or a whole bunch of sections.
Choose a single section for which you will be contributing and raise a new issue.
