### ISSUE TITLE
[Add Content] Add Content for Linked List Topics

### ISSUE THREAD

**Issue by revanth1718** [animator/learn-python#581]
I would like to contribute to the repository by adding comprehensive content on Linked Lists. This will include an introduction to linked lists, different types (singly, doubly, and circular linked lists), and various operations (insertion, deletion, traversal, etc.).

I am Participating in GSSOC'24

**Comment by somyagupta05** [comment]
Hello sir, 
I would like to contribute by adding a valuable content for linked list topics. Which will contain different types of linked list and various operations such as insertion, deletion, reverse, traversal, etc on each type of linked list.

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.
