### ISSUE TITLE
Supervised Learning and Unsupervised Learning

### ISSUE THREAD

**Issue by Kazasunitha** [animator/learn-python#586]
Differences between supervised learning and unsupervised learning , Algorithms used in supervised and unsupervised learning.

**Comment by Kazasunitha** [comment]
I request you to assign this task to me under Gssoc 24 and label it

**Comment by akshitajaiswal2908** [comment]
i request you please assign me this task under Gssoc 24 and label it as am starting my journey in open source

**Comment by aditisaxena259** [comment]
I understand the need and implementation of supervised and unsupervised machine learning algorithms.. I request you to assign me this project

**Comment by animator** [comment]
Already done.
