### ISSUE TITLE
Introduction to line chart in Matplotlib

### ISSUE THREAD

**Issue by Dishika18** [animator/learn-python#588]
I want to contribute a new section in [plotting-visualisation](https://github.com/animator/learn-python/tree/main/contrib/plotting-visualization) directory explaining the generation and manipulation of line chart using Matplotlib in Python. I will craft a comprehensive guide on generating a variety of line charts using Matplotlib. 

Expected Level: Level 2

@animator Please assign this issue to me under GSSoC'24.

**Comment by akashlogics** [comment]
I want to contribute a new section in [plotting-visualisation](https://github.com/animator/learn-python/tree/main/contrib/plotting-visualization) directory explaining Simple line styles can be defined using the strings "solid", "dotted", "dashed" or "dashdot"

Expected Level: Level 2
@animator  Please assign this issue to me under GSSoC'24.
