### ISSUE TITLE
Introduction to Scatter plot in Matplotlib 

### ISSUE THREAD

**Issue by Dishika18** [animator/learn-python#589]
I want to contribute a new section in [plotting-visualisation](https://github.com/animator/learn-python/tree/main/contrib/plotting-visualization) directory explaining the generation and manipulation of Scatter plot using Matplotlib in Python. I will craft a comprehensive guide on generating a variety of Scatter Plot using Matplotlib.

Expected Level: Level 2

@animator Please assign this issue to me under GSSoC'24.

**Comment by akashlogics** [comment]
I want to contribute in this issue. and I have many example programs related to Matplotlib
Can you assign me and label it GSsoc, 24.
