### ISSUE TITLE
Introduction to Pie Charts in Matplotlib

### ISSUE THREAD

**Issue by anamika23428** [animator/learn-python#591]
Hello @animator 
I want to add a new section in [plotting-visualisation](https://github.com/animator/learn-python/tree/main/contrib/plotting-visualization) directory explaining the generation of Pie Chart using Matplotlib in Python. 

@animator Please assign this issue to me under GSSoC'24.

**Comment by piyush-poddar** [comment]
Hi @anamika23428, there is already an [issue](https://github.com/animator/learn-python/issues/546) opened for this and assigned to someone else. You can wait for it to be closed.

**Comment by anamika23428** [comment]
ok @piyush-poddar

**Comment by Priti9075** [comment]
I'm incredibly enthusiastic about tackling the "Introduction to Pie Charts in Matplotlib " issue for GSoC 2024!
