### ISSUE TITLE
Adding Content on "Adding and Deleting Columns in Dataframe" under Pandas Module

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [animator/learn-python#600]
Adding and removing columns are common operations that can significantly impact the usability and performance of your data. This issue delves into best practices for dynamically modifying DataFrames, ensuring data integrity and optimizing workflow efficiency.

@animator , Please assign me this issue

**Comment by radharashmitha** [comment]
Hi! @Santhosh-Siddhardha, I noticed that there is a need to add content related to "Adding and Deleting Columns in Dataframe" under the Pandas module. I would like to take up this task and contribute to the project under Gssoc'24. Please assign to me

### Proposed Solution
I will create a new section in the documentation that covers how to add and delete columns in a Pandas DataFrame. This will include examples, explanations, and best practices.
