### ISSUE TITLE
Project - Retail Management System in Python

### ISSUE THREAD

**Issue by piyush-poddar** [animator/learn-python#601]
## Project Description
The proposed python project **SHOPIFY - RETAIL MANAGEMENT SYSTEM** is an engineering approach to enhance current retail shop management and customer billing activities. The software works as a self-service product for retail frontline representative while selling the products and generating customer bill at the same time.

**Approach:** I'll implement the software in Python along with Mysql database as well as using mysql.connector to connect with python.

Expected Level: **Level 3**

Please assign me this issue @animator. Thanks!!

## A Preview of what the application will look like

**Product and Inventory Management:**

![image](https://github.com/animator/learn-python/assets/143445461/4119bdc1-ee47-4bce-a5d6-e0da850d45d7)

**Bill Generator:**

![image](https://github.com/animator/learn-python/assets/143445461/a2b53fb4-603c-41f8-8e13-c22b0779e3e4)

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.

**Comment by piyush-poddar** [comment]
@animator I want to contribute this project in the Mini-Projects section. I have seen that we can contribute mini-projects in **contributing.md** and many other contributors doing so. Please let me contribute this project.
