### ISSUE TITLE
File Handling in python

### ISSUE THREAD

**Issue by kyra-09** [animator/learn-python#607]
Aim :- file handling techniques to read , write and manipulate files in python

@animator kindly assign me this issue

**Comment by Dhruv100404** [comment]
I am Working On this for a long time I can contribute to it very well as I am Pursuing  for Data Analyst role
assign it to me @animator

**Comment by Charu19awasthi** [comment]
can you please assign me this issue i can do it perfectly @animator

**Comment by animator** [comment]
Content is already added.
