### ISSUE TITLE
Add Tkinter module of Python

### ISSUE THREAD

**Issue by Chandana-756** [animator/learn-python#609]
I would like to provide a step-by-step guide to using the standard Python GUI module, Tkinter, to develop a Tkinter GUI Application. Tkinter makes it quick and simple to construct desktop programs and is a thin object-oriented layer for the Tcl/Tk GUI toolkit. 

I am interested in working on this issue as part of GSSOC'24.

**Comment by Dhruv100404** [comment]
I have Worked Very Well On the Tkinter library created multiple Codes on it I am ready to contribute to it as well

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.
