### ISSUE TITLE
Add machine learning algorithms and data representation functions

### ISSUE THREAD

**Issue by metdiksha** [animator/learn-python#613]
Hello @animator , I would like to add more Machine Learning algorithms, also pictorially represent data before and after the implementation. This would act as a machine-learning tutorial for beginners.

I would like to take this task under GSSOC'24.

Thanks.

**Comment by animator** [comment]
Topic is not clear.

**Comment by animator** [comment]
Pick another topic from Contributing Guide and raise a new issue.
