### ISSUE TITLE
[Add Content] Introduction to Arrays

### ISSUE THREAD

**Issue by PilotAxis** [animator/learn-python#616]
Hey @animator, I would like to add content on the topic "Introduction to Arrays". In this topic, I will add some basic and important key concepts of Arrays in Python. 

Topics I will be covering -
1. Introduction
2. Example to explain Arrays
3. Operations on Arrays such as Traversal, Insertion, Deletion, Searching and Sorting etc.
4. Advantages and Disadvantages
5. Only basic info about Multi-dimensional array.

Please assign this issue to me @animator !

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.
