### ISSUE TITLE
[Add Content]: Creating Neural Network from using Python

### ISSUE THREAD

**Issue by rahulnarayaniitk** [animator/learn-python#623]
Hey @animator , 
I would like to raise an issue regarding creating a Neural Network from Scratch using Python.
This will be very beneficial for learners who are new to Machine Learning and Deep Learning but have basic knowledge of Python.
Kindly assign me this issue and provide a level 3 under GSSoC '24.

Thanking you.

**Comment by animator** [comment]
Content is already added. Raise a new issue if you want to improve.
