### ISSUE TITLE
Add Content: Add Convolutional Neural Networks (CNN) Topic

### ISSUE THREAD

**Issue by sreevidya-16** [animator/learn-python#634]
Please assign me. 

I am Participating in GSSOC'24.

**Comment by akashlogics** [comment]
I would like to. Work on this issue as I'm studying Artificial intelligence and data science and have learned more about Convolutional Neural Networks (CNN) and many examples. So can you please assign me this problem
and label it GSSoc 24

I hope this will be the first issue I will be solving with full effort as a contributor

@animator Thank you
