### ISSUE TITLE
Add Mini Project: A Password Generator

### ISSUE THREAD

**Issue by abhi-la-sha** [animator/learn-python#636]
I would like to add a Password generator that will take user input for the length of the password he/she wants and generate a random password. This model will also have a GUI.
This will help the users learn using modules like:
1. Tkinter
2. Random

@animator Kindly add the labels and assign this issue to me.

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.
