### ISSUE TITLE
ADD-Crop Recommendation A  ML Mini Project 

### ISSUE THREAD

**Issue by saikrishna823** [animator/learn-python#637]
I would like to add crop recommendation and classification project which can one can use it as mini project.This machine learning project will help others to get idea of various ml classification algorithms.I will use best algorithm that gives maximum accuracy.I will also implement web application using streamlit for users to use this.Please assign this issue to me.

**Comment by saikrishna823** [comment]
Hi @animator  As it is a ml project,what files should i include?Can I add  crop_recommendation.ipynb file,app.py file or Can I create a folder for this mini project?

**Comment by animator** [comment]
mini projects are no longer allowed. Pick another topic from Contributing Guide and raise a new issue.
