### ISSUE TITLE
Adding Apriori Algorithm to Machine Learning Section

### ISSUE THREAD

**Issue by Chandana-756** [animator/learn-python#639]
I've noticed that the Apriori Algorithm is missing from this section. It's important because it helps find frequent itemsets and association rules in large datasets.

I'd like to provide a description of this algorithm by explaining its steps, how it works, its advantages, disadvantages, and also sharing a Python implementation.

I'm interested in working on this issue for GSSOC'24.

**Comment by bubblepreetkaur06** [comment]
Apriori is one of the important algorithm for extracting the frequent item data items by generating candidate item sets and helps a lot in Data mining and Analysis. Kindly assign me this issue under GSSoc'24.

**Comment by Chandana-756** [comment]
I have made the pull request #759 . Kindly check it once
