### ISSUE TITLE
Adding python flask as a backend module

### ISSUE THREAD

**Issue by NIKITA320495** [animator/learn-python#64]
Incorporate Flask into the project to enhance its functionality and interactivity. By integrating Flask, you can develop dynamic web pages, handle user requests, and serve content efficiently. This addition allows for the creation of interactive features such as user authentication, data submission forms, and real-time updates, enhancing the overall user experience and engagement with the application.

**Comment by animator** [comment]
You cannot choose an entire topic or more than one section.
Choose a single small section for which you will be contributing and raise a new issue.
