### ISSUE TITLE
[UI] : Add a custom scroll bar

### ISSUE THREAD

**Issue by SaranshBangar** [animator/learn-python#645]
Description -> Adding a custom scroll bar can enhance UX and improve user retention

Image ->

![image](https://github.com/animator/learn-python/assets/114401238/a3ab600c-54d5-4468-a049-e70ba0ef19fb)

**Comment by SaranshBangar** [comment]
Resolved in PR #646

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.
