### ISSUE TITLE
[UI] : Add a custom favicon

### ISSUE THREAD

**Issue by SaranshBangar** [animator/learn-python#647]
Description -> As of now the favicon is the default image, we can replace that with the Python logo to make the website look more appealing

Image ->

![image](https://github.com/animator/learn-python/assets/114401238/8172f681-65c0-4c57-8289-0c815384d904)

**Comment by animator** [comment]
This topic is not under the scope of this project. Pick another topic from Contributing Guide and raise a new issue.
