### ISSUE TITLE
[ADDITION]: Adding Data Visualization with Python

### ISSUE THREAD

**Issue by Dishika18** [animator/learn-python#66]
Data visualization provides a good, organized pictorial representation of the data which makes it easier to understand, observe, analyze.
I can add about Matplotlib library in detail to this website by providing proper graph visualization and code snippet for the same. 
Please assign this issue to me under GSSoC'24.
Thank You 
Dishika

**Comment by animator** [comment]
You cannot choose an entire topic or more than one section.
Choose a single small section for which you will be contributing and raise a new issue.
