### ISSUE TITLE
include the usage of numpy library

### ISSUE THREAD

**Issue by keerthi-ganiger** [animator/learn-python#67]
since the repository already consists of all the basic python learning material. I want to enhance the quality by introducing the details about numpy library, its usage with examples for the better understanding

**Comment by animator** [comment]
Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. 

Also, you cannot choose an entire topic or more than one section.
Choose a single small section for which you will be contributing and raise a new issue.
