### ISSUE TITLE
MY NAME IS NOT ON THE LEADERBOARD

### ISSUE THREAD

**Issue by Kavin56** [animator/learn-python#708]
I have contributed to this repository and still my name is not on the leaderboard.
https://github.com/Kavin56/learn-python/pull/2
https://github.com/Kavin56/learn-python/pull/1

**Comment by animator** [comment]
Because you are creating PRs and merging it in your own forked repository. You have to get your PRs merged in this repository which is the main repository.

**Comment by Kavin56** [comment]
@animator can i give pull request again.
