### ISSUE TITLE
Addition of binary tree

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#718]
I would like to add binary tree along with it's basic operations.

**Comment by strawberrydontlie** [comment]
I'd like to working on Addition of binary Tree.
I'm a GSSoC'24 contributor.
I want to work on this issue.Please assign me this issue.
Also please add the labels gssoc and the level which you find appropriate for this issue. thank you!

I will base on info below to add the additional info about binary tree.
First, I will introduction to Binary Trees
Then, Show how to adding Elements to a Binary Tree
After that I will give Methods of Adding Elements (Top-down Approach &Level-order Insertion)
Moreover, I will explain considerations for Adding Elements. 
For example: Maintaining balance in the tree is crucial to ensure efficient operations like search, insert, and delete. Unbalanced trees can degrade performance, leading to increased time complexities. Balance or not is really important to binary tree. 
Finally, I will show the different kinds of binary tree and give explanation: Complete Binary Tree /Full Binary Tree/ Perfect Binary Tree/Balance Binary Tree and etc.
![IMG_3796](https://github.com/animator/learn-python/assets/110859339/9a8c3e18-d996-4131-b40f-6cf0e41cca76)
 
 
  
![IMG_3797](https://github.com/animator/learn-python/assets/110859339/9b02b6ef-cd31-48b0-b942-94c5383bebb0)
