### ISSUE TITLE
Adding Linked List

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#72]
I would like to add the topic "Linked List" to the content. Please assign this issue to me. Thank you.

**Comment by Sudiksha18** [comment]
@miss-panchal miss-panchal please assign this task i am good at python and done some projects

**Comment by eshapriyanka** [comment]
I would like to work on this issue. Please assign this issue to me as well.

**Comment by Vedant285** [comment]
I would like to add more on linked list

**Comment by ArismitaM** [comment]
I have worked with linked lists before and would love to add more on linked lists in this section, please assign this task to me.

**Comment by animator** [comment]
Closing as no PR has been raised so far.

**Comment by Ishita-Jena** [comment]
Hello, since this issue is closed, does this mean I cannot raise a pull request anymore?

**Comment by animator** [comment]
You can raise a new issue. I will assign it to you.
