### ISSUE TITLE
Adding OOPs concept under the topic Advanced python.

### ISSUE THREAD

**Issue by lakshay-111** [animator/learn-python#73]
Please assign me this issue so that I can work on this project on adding blog about OOPs concept in python and contribute in it for GSSOC' 24.

**Comment by Sudiksha18** [comment]
@miss-panchal miss-panchal please assign this task i am good at python and done some projects

**Comment by ScriptSherpa** [comment]
@animator please assign this task i am 
good at python and done some projects

**Comment by animator** [comment]
@Sudiksha18 @ScriptSherpa Go through the Contributing guide and raise your own issue for a new task.

**Comment by Akshitha28112004** [comment]
Hey I've learned oops concepts through Java and I can give you a detailed explanation of the oops concepts through python so can you please assign me this issue under GSSOC'24?

**Comment by lakshay-111** [comment]
I raised a PR today only. But you didn't merged it.

**Comment by animator** [comment]
You did not link this issue in the PR description.
Try to follow the instructions properly from next time.
