### ISSUE TITLE
Add content of Sets 

### ISSUE THREAD

**Issue by lovelymahor** [animator/learn-python#731]
I'd like to add more content of Sets in Python. This could include Set Items, Unordered,  Unchangeable, The set() Constructor etc

I'm a GSSoC'24 contributor.

I want to work on this issue.Please assign me this issue.

Also please add the labels gssoc and the level which you find appropriate for this issue. thank you!

**Comment by strawberrydontlie** [comment]
I want to add content of sets. I will give the users the most comprehensive explanation of set based on the following information. And I'm a GSSoC'24 contributor. Plz assign to me :)

1⃣️ Definition and Creation of Sets:
    1) I will explain what sets are and how they differ from lists or tuples.
    2) Then I will show how to create a set using curly braces `{}` or the `set()` function.
    3) And I will note that an empty set can only be created with `set()`, as `{}` is used to create an empty dictionary.

2⃣️ Characteristics of Sets: (give them conecpt here)
   1)  Sets contain unique elements, with no duplicates allowed.
   2) Sets are unordered, meaning the storage order of elements is not maintained.
   3) Elements must be immutable, meaning mutable types like lists cannot be included.

3⃣️ Basic Operations on Sets:
   1) 'add()' method to adding elements.
   2) 'remove()', 'discard()', and 'pop()' methods to removing elements.
   3) 'clear()' method to clearing all elements from a set.

4⃣️ Uses and Advantages of Sets:
   1) Discuss the use of sets for removing duplicates.
   2) Highlight the efficiency of set operations, especially for membership tests and deduplication in large datasets.

5⃣️ Mathematical Operations with Sets:
   1) Introduce union (`union`), intersection (`intersection`), difference (`difference`), and symmetric difference (`symmetric_difference`) of sets.
   2) Show how to perform these operations using methods and operators (like `|`, `&`, `-`, `^`).

6⃣️ Limitations of Sets:
   1) Discuss the inability of sets to perform indexing and slicing operations.
   2) Explain why sets do not support these operations and how to handle situations where order is necessary.

Base on these 6 sections, I will fully explain the concept and operations of sets in Python, enabling them to better utilize sets in their programming endeavors.
