### ISSUE TITLE
Add topic of Classes/Objects 

### ISSUE THREAD

**Issue by lovelymahor** [animator/learn-python#732]
I'd like to add content of Classes/Objects in Python. This could include inheritance, iterators, polymorphism etc

I'm a GSSoC'24  contributor.

I want to work on this issue.Please assign me this issue.

Also please add the labels gssoc and the level which you find appropriate for this issue. thank you!

**Comment by TanishaVerma-08** [comment]
Hello there, I am a GSSoC'24 contributor and i would like to add some content about Classes/Objects in Python. 
I would like to add some examples related to inheritance and its types.
Also, I would like to mention some real-world examples and how the concept of Object Oriented Programming is used in python.
I would like to work on this issue, kindly assign me one.

**Comment by 1754riya** [comment]
I want to add content about Classes/Objects in Python. 
I am a GSSoC'24 contributor and I would like to work on this issue. Please assign this issue to me
