### ISSUE TITLE
learning pandas and numpy library with python with sample example and  explanations  

### ISSUE THREAD

**Issue by akashlogics** [animator/learn-python#735]
I learned all the functions present in both libraries Pandas and Numpy and have many  example programs and explanations of each steps to use the libraries in python and I would like to PR in this project.

@animator I would like to work on this issue can you please assign me 
And label it GSsoc 24

**Comment by strawberrydontlie** [comment]
I'd like to give the info about learning pandas and numpy library with python with sample example and explanations. 
I'm a GSSoC'24 contributor.
I want to work on this issue.Please assign me this issue.
Also please add the labels gssoc and the level which you find appropriate for this issue. thank you!

First I will give the introduction about NumPy and pandas. 
Next, NumPy sample and explanation Overview:
1️⃣ Essential library for scientific computing in Python.
2️⃣ Supports large, multi-dimensional arrays and matrices.
3️⃣ Offers a vast collection of mathematical functions to operate on arrays.

After that, pandas sample and explanation Overview:
1️⃣ Library for data manipulation and analysis.
2️⃣ Provides powerful data structures like DataFrames.
3️⃣ Ideal for working with structured data.                                                                                                                                      These are basic ideas about this issue, and I want to help users to comprehensively understand pandas and numpy library though examples I provide.

**Comment by akashlogics** [comment]
@strawberrydontlie i had already done my sample files and libraries function and I am waiting for the admin to assign me so I can PR next minute
