### ISSUE TITLE
Add Content: Itertools Module in Python

### ISSUE THREAD

**Issue by piyush-poddar** [animator/learn-python#742]
I want to add content related to `itertools` module in Python, in [advanced-python](https://github.com/animator/learn-python/tree/main/contrib/advanced-python) directory.

I will add explaination, code and examples related to various functions in `itertools` module like `Combinations()`, `Permutations()`, `accumulate()` , etc.

Expected Level: **Level 2**

@animator Please assign this issue to me under GSSOC'24.

**Comment by lovelymahor** [comment]
@animator Please assign this issue to me under GSSOC'24.

**Comment by rsm08** [comment]
I'm also interested in solving this issue please give me opportunity.
