### ISSUE TITLE
Add Content: List Methods in Python

### ISSUE THREAD

**Issue by piyush-poddar** [animator/learn-python#743]
I will add the syntax, code and examples with relevant outputs for all the list methods in Python in [advanced-python](https://github.com/animator/learn-python/tree/main/contrib/advanced-python) directory.

Expected Level: **Level 2**

@animator Please assign this issue to me under GSSOC'24.

**Comment by animator** [comment]
@piyush-poddar Issue bombing is not allowed in this repo. Restrict yourself to working on 2-3 issues at a time. This and other issues have been closed.
