### ISSUE TITLE
PATTERN PROBLEM

### ISSUE THREAD

**Issue by miss-panchal** [animator/learn-python#75]
adding pattern problem in loop will give learner better understanding of language and help to build logic

**Comment by Sudiksha18** [comment]
@miss-panchal miss-panchal please assign this task i am good at python and done some projects

**Comment by Priyadeara2427** [comment]
Hello project admin, I would like to work in this issue as i am much familiar with python and excellent in solving pattern . I request you to please assign this issue to me. Thank you.

**Comment by Akshitha28112004** [comment]
Hey I have solved different types of questions in different websites in c python and Java on pattern printing so can you please assign me this issue under GSSOC'24?
