### ISSUE TITLE
how to install  pandas library

### ISSUE THREAD

**Issue by keerthi-ganiger** [animator/learn-python#76]
I want to add details about installing pandas library for its usage with proper screenshots using pip install and jupyter notebooks.

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to resolve the issue first before being assigned a new issue.

**Comment by deekshithapalla** [comment]
I would like to work on "installation of pandas library" issue. Please assign this task to me.

**Comment by animator** [comment]
@deekshithapalla done

**Comment by shreyasadhasivam** [comment]
I would like to work on this

**Comment by Tejasri-Pendota** [comment]
Hello sir,

I would like to address this issue by providing detailed, step-by-step instructions on how to install the Pandas library. 
**I will use real screenshots taken during the installation process on my own laptop**. 
These screenshots will make the instructions highly relatable and helpful for users.
