### ISSUE TITLE
Adding Stack

### ISSUE THREAD

**Issue by Ishita-Jena** [animator/learn-python#77]
I would like to add "Stacks" to the content. Please assign this issue to me. Thank you.

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to resolve the issue first before being assigned a new issue.

**Comment by animator** [comment]
Closing as no PR has been raised so far.

**Comment by Ishita-Jena** [comment]
Hello, I would like to raise a pull request for stacks. Please let me know if i can. Thank you
