### ISSUE TITLE
installing numpy

### ISSUE THREAD

**Issue by keerthi-ganiger** [animator/learn-python#78]
I want to add details about installing numpy library for its usage with proper screenshots using pip install and jupyter notebooks.

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to resolve the issue first before being assigned a new issue.

**Comment by Yodha-Sudarsi** [comment]
"Hi animator, I'd like to help by taking on the task of installing NumPy. Could you please assign it to me?

**Comment by animator** [comment]
Sure @Yodha-Sudarsi assigned.

**Comment by Yodha-Sudarsi** [comment]
Hi animator, thank you for assigning installing numpy #78. My doubt is in [CONTRIBUTING.md](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md) the list of sections should be same as the "Some Content Ideas" for NumPy or I have to add more topics the list of sections.

**Comment by animator** [comment]
@Yodha-Sudarsi Your task is to add a document on how users can install numpy.

**Comment by Yodha-Sudarsi** [comment]
Hi @animator, successfully sent a pull request. Added how to install NumPy step-wise. Waiting for the feedback and things to works upon further.

**Comment by Yodha-Sudarsi** [comment]
Hi @animator , can I move to new issues or any feedback. This was my very first pull request.
