### ISSUE TITLE
Add Mini Project: Iris Flower classification.

### ISSUE THREAD

**Issue by Jaya-Prakash-17** [animator/learn-python#780]
@animator I would like to contribute to the repository by adding a mini project which classifies the iris flowers, this will be a simple yet  informative project where user will learn how to load the data clean it and perform EDA and then classification.

I am participating in GSSoC'24 and am eager to contribute to this project.

**Comment by animator** [comment]
mini projects are no longer allowed. Pick another topic from Contributing Guide and raise a new issue.
