### ISSUE TITLE
Add content segment: sorting algorithms 

### ISSUE THREAD

**Issue by Jaya-Prakash-17** [animator/learn-python#781]
@animator sorting algorithms are the most fundamental yet important topic in DSA for interviews. Many of the freshers struggle with fundamental sorting algorithms like bubble sort.

So kindly let me add content on 5 most important sorting algorithms so users can have easy time learning these sorting techniques. 

So kindly assign this issue to me.

Thankyou

**Comment by rsm08** [comment]
In computing, algorithms are needed to design computer programs.
My hope is that through solving this issue  I'll be able develop new skills & can also be able to provide clarity for learners.
