### ISSUE TITLE
Add about pip

### ISSUE THREAD

**Issue by lovelymahor** [animator/learn-python#784]
Add the content about What is PIP? How to insall it? How to Check if PIP is Installed? How to download package etc.

Please assign it to me I want to work on this 
Thankyou 

Also please add the labels gssoc and the level which you find appropriate for this issue. 
thank you!

**Comment by rsm08** [comment]
please add the level so we can start working

**Comment by PragyaChauhan1401** [comment]
@animator Please assign me this issue

I am a GSSOC contributor
