### ISSUE TITLE
Adding Content on Magic Methods under Advanced Python module

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [animator/learn-python#785]
I aim to enhance the Advanced Python module by adding a detailed section on Magic Methods (also known as dunder methods or special methods). Magic Methods are a cornerstone of Python's object-oriented programming, allowing developers to define the behavior of objects with built-in operations. 

@animator Please assign me this issue.

**Comment by rsm08** [comment]
hello @animator 
I would like to add content about magic methods in advance python.
Magic methods are specialized methods, denoted by double underscores, that wield the power to transform the behavior of Python classes in fascinating ways. I would like explain them in detail.
so please assign this issue to me .
Thank You.
