### ISSUE TITLE
Add a chapter about the use of Machine learning in python (A basic introduction)

### ISSUE THREAD

**Issue by mdphaye** [animator/learn-python#788]
How to use python as a Machine Learning tool. Description about Basic as well as Advanced machine learning libraries to import various ML algorithms using python. Use, implementation and syntax of each machine learning algorithm in a structured format. 

@animator Please assign this to me under GSSoC'24. I want to work on this, and create an easy to understand, basic step-by-step overview for beginners in ML to approach the field using python as an efficient tool.
I am eager to contribute to this project.
Expected level: Level 2
Thank you

**Comment by animator** [comment]
Pick another topic from Contributing Guide and raise a new issue.
