### ISSUE TITLE
ADDING ARRAY AND LINKED LIST TYPE DATA STRUCTURE

### ISSUE THREAD

**Issue by miss-panchal** [animator/learn-python#79]
i want to add a section in advanced programming in which array , linked list , stack and queue and their basic implementation will be done

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to resolve the issue first before being assigned a new issue.

**Comment by miss-panchal** [comment]
i have done previous issue.
in this we can start a dsa section because implementation of data structure like array , linked list or tree are very different .
in language like c++ or java, we declare arr but in this we use list

**Comment by Akshitha28112004** [comment]
Hey Iam good at c python and Java and I can give you a detailed explanation and related examples so can you please assign me this issue under GSSOC'24?

**Comment by animator** [comment]
Closing as no PR has been raised so far.

**Comment by miss-panchal** [comment]
i will raise a PR tomorrow.
please give some time
i am preparing that only .

**Comment by animator** [comment]
ok
