### ISSUE TITLE
Mini Project : Alarm clock

### ISSUE THREAD

**Issue by sreevidya-16** [animator/learn-python#791]
I want to make an application that allows users to set alarms with snooze and stop options, and is a good way for beginners to learn how to handle time and date in Python.

@animator  Please assign me this issue
 
I am participating in GSSOC'24

**Comment by PragyaChauhan1401** [comment]
@animator Please assign me this issue

I am a GSSOC contributor

**Comment by B8indu** [comment]
I WOULD LIKE TO DO THIS PROJECT 
@animator  please assign me this issue
