### ISSUE TITLE
Mini Project - Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by sreevidya-16** [animator/learn-python#793]
I want to create a Fibonacci Number Sequence Generator and Detector Project
It prints the fibonacci Series, when we give length as input and also It detects whether a particular number is in the sequence or not

@animator  Please assign this issue to me

I am Participating in GSSOC'24

**Comment by B8indu** [comment]
@animator please assign me this isuse
I am Participating in GSSOC24
