### ISSUE TITLE
Add light and dark mode feature to the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [animator/learn-python#8]
Please assign me this issue under GSSOC'24.

**Comment by Tahasildarrashid** [comment]
I have my own portfolio created and there is this option of toggling from dark mode to light mode! So can u assign me this issue under GSSOC'24.
It would be of a great help!

**Comment by krish-san** [comment]
Hi !
I'm experienced in website development and have a keen eye for aesthetics. I'm interested in contributing to the issue of implementing light and dark mode toggles on the web. Please assign me this issue under GSSoc'24

**Comment by iamrudhresh** [comment]
Please assign me to this issue under GSSOC'24

**Comment by animator** [comment]
@Sneha123-zudo @Tahasildarrashid @Hemav009 @iamrudhresh @krish-san Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
