### ISSUE TITLE
supervised learning 

### ISSUE THREAD

**Issue by keerthi-ganiger** [animator/learn-python#81]
i want to include basic details about supervised learning which includes classification and regression with general examples.

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to resolve the issue first before being assigned a new issue.

**Comment by Praneeth2312** [comment]
hey @animator can you please assign this issue to me I am willing to contribute under this section!
i am a GSSOC'24 contributor

**Comment by animator** [comment]
Closing as no PR has been raised so far.
