### ISSUE TITLE
Adding Content to Operations on Arrays topic in Numpy Module

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [animator/learn-python#83]
Hi @animator ,
NumPy is a fundamental library for scientific computing in Python, providing powerful tools for working with arrays and matrices. This issue proposes the expansion of content focused on "Operations on Arrays" within the NumPy module, covering a range of essential operations and techniques for manipulating arrays.

I am interested in working with this issue. Please assign to me.

**Comment by animator** [comment]
Only one section is assigned to a person at a time. You need to resolve the issue first before being assigned a new issue.

**Comment by Priyadeara2427** [comment]
Hello project admin @animator , I would like to work on this issue as I am good in NumPy module and would like to contribute towards operations on arrays. Please assign this issue to me under gssoc level1, or level 2. Thank you.

**Comment by animator** [comment]
@Priyadeara2427 assigned.

**Comment by animator** [comment]
Closing as no PR has been raised so far.
