### ISSUE TITLE
[Addition] of a section python intraction with MySql database .

### ISSUE THREAD

**Issue by Riya922003** [animator/learn-python#85]
Feature : Adding a section of python interaction with MySql database which will come under the topic interacting with databases mentioned in contributors.md

Topics that will be covered under this section are:

1. Basics of MySql 
2. Connecting MySql database with python 
3. MySql queries through python 
4. Mysql practice questions using python
5.Some python mini projects 

I would appreciate if the issue is being assigned .

**Comment by Sanmita-Paul** [comment]
@animator 
I can add concepts of Python MySQL with examples which help the readers to understand the concept easily. I would like this issue to be assigned to me as part of GSSoC'24 with the gssoc label and the appropriate level (1).
Thank you

**Comment by animator** [comment]
You cannot choose an entire topic or a whole bunch of sections.
Choose a single section for which you will be contributing and raise a new issue.

Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)

**Comment by Sanmita-Paul** [comment]
> You cannot choose an entire topic or a whole bunch of sections. Choose a single section for which you will be contributing and raise a new issue.
> 
> Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)

I would like to work upon interacting with databases
