### ISSUE TITLE
About K-nearest neighbor (KNN) algorithm in ML in python

### ISSUE THREAD

**Issue by MrCodYrohit** [animator/learn-python#860]
I will add details about K-nearest neighbor (KNN) ML algorithm in Python and explain it with code snippets, also try to generalized it when to use it or not.

**Comment by MrCodYrohit** [comment]
@animator  Please assign this issue to me under GSSOC'24.

**Comment by Pjdash** [comment]
I have recently learned ML in my semester .Thus can provide in depth explanation about k means using psuedo code and syntax...plz assign this project to me
