### ISSUE TITLE
hover effect 

### ISSUE THREAD

**Issue by thesri** [animator/learn-python#9]
hover effect on the star this book on github below the learn python and increasing its font size would make it easily visible.please assign it under gssoc 24

**Comment by OmChillure** [comment]
@animator Can you please assign this issue to me under GSSoc'24 !!

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by aditi-sharma-2004** [comment]
Hi, Aditi Sharma this side , I would love to work on this issue.

**Comment by iamrudhresh** [comment]
Please assign me to this issue under GSSOC'24.

**Comment by animator** [comment]
@thesri @hasmithagunda123 @aditi-sharma-2004 @iamrudhresh @OmChillure @anvishelar Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process. It will be assigned to you and you can send the PR.
