### ISSUE TITLE
Content in the Web Scraping section

### ISSUE THREAD

**Issue by Sunainabhave** [animator/learn-python#91]
I would like to add content under the web scraping section.
Please assign me this task under GSSOC'24.

thank you!

**Comment by animator** [comment]
What content?

Please go through the [Contributing Guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md), raise a new issue as per the described process.

**Comment by Sunainabhave** [comment]
Sorry, I would like to add content regarding Beautiful Soup.

**Comment by animator** [comment]
Beautiful Soup is a big section in itself. Choose a single small section for which you will be contributing and raise a new issue.

**Comment by Sunainabhave** [comment]
Improve Documentation for HTML Parsing in Beautiful Soup

**Comment by animator** [comment]
@Sunainabhave This issue is already closed. You need to raise a new issue.
