### ISSUE TITLE
Add Plotting and visualisation section 

### ISSUE THREAD

**Issue by adarsh1001111** [animator/learn-python#93]
I want to add Plotting and visualisation of data using the matplotlib and extend its usage to .csv files  in python.
You can assign this issue to me @animator .

**Comment by animator** [comment]
You cannot choose an entire topic or more than one section.
Choose a single small section for which you will be contributing and raise a new issue.

**Comment by adarsh1001111** [comment]
In this case i can add about matplolib with its installation.
