### ISSUE TITLE
Improve Documentation for HTML Parsing in Beautiful Soup under Web Scraping

### ISSUE THREAD

**Issue by Sunainabhave** [animator/learn-python#95]
This issue involves enhancing the documentation under the "Beautiful Soup" section of the Web Scraping documentation by providing clearer explanations and examples specifically related to parsing HTML documents.

**Comment by VarsaGupta** [comment]
Hey, I would like to work on it. Please assign me the issue.

**Comment by Sunainabhave** [comment]
@animator i had few doubts about regarding this contribution. Should i create a vanilla js website and then add the contents?
just having these confusions. I tried contacting mentors in discord, could'nt get any response

**Comment by animator** [comment]
Follow the contributing guide. Everything is clearly written there.
Also see some merged PRs to get a good idea.
