### ISSUE TITLE
[Mini projects]: Expense Tracker Python Project

### ISSUE THREAD

**Issue by Riya922003** [animator/learn-python#98]
The expense tracker project in Python helps you track how much money you are spending. It keeps a record of your spending and lets you figure out where you can save money. It can also give you advice on how to manage your finances better.

please assign this issue

**Comment by Yodha-Sudarsi** [comment]
Hi @animator ,  I'd like to help by taking on the Mini projects: Expense Tracker Python Project. Could you please assign it to me?

**Comment by Yodha-Sudarsi** [comment]
Hey @Riya922003 , if you need help with anything, I've got experience with expense trackers from a personal project. 
Feel free to reach out. 
-**Happy coding**!
